Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2020-10, with the labels that each got.

#34 Ak hotfix vnet azurecaf
  modules/networking/virtual_network/module.tf
Labels: breaking-change

#57 WIP - 0.4
  .devcontainer/docker-compose.yml
  .github/workflows/master-100.yaml
  .github/workflows/master-200.yaml
  app_service_environments.tf
  azuread.tf
  bastion_service.tf
  examples/app_insights/100-all-attributes/configuration.tfvars
  examples/app_insights/100-simple/configuration.tfvars
  examples/backend.azurerm
  examples/compute/container_registry/100-simple-acr/configuration.tfvars
  examples/compute/container_registry/200-acr-private-link/configuration.tfvars
  examples/compute/container_registry/200-acr-vnet/configuration.tfvars
  examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars
  examples/compute/virtual_machine/101-single-windows-vm/configuration.tfvars
  examples/compute/virtual_machine/102-single-vm-data-disks/configuration.tfvars
  examples/compute/virtual_machine/103-multiple-vm/multiple_vm.tfvars
  examples/data_analytics/200-basic-ml/configuration.tfvars
  examples/data_analytics/200-basic-ml/networking_spoke.tfvars
  examples/data_analytics/200-basic-ml/readme.md
  examples/databricks/100-simple-databricks/configuration.tfvars
  examples/main.tf
  examples/mssql_server/200-mssql-two-regions.tfvars
  examples/mssql_server/200-mssql.tfvars
  examples/networking/private_dns/100-private-dns-vnet-links/configuration.tfvars
  examples/networking/private_dns/100-private-dns-vnet-links/readme.md
  examples/networking/virtual_network/100-subnet-delegation/configuration.tfvars
  examples/output.tf
  examples/redis_cache/100-redis-standard/configuration.tfvars
  examples/scripts/cloud-init/install-rover-tools.config
  examples/solution.tf
  examples/variables.tf
  examples/webapps/appservice-environment/101-simple_ase/configuration.tfvars
  examples/webapps/appservice/101-appservice-simple/configuration.tfvars
  examples/webapps/appservice/102-appservice-slots/configuration.tfvars
  examples/webapps/appservice/103-appservice-extend/configuration.tfvars
  keyvault.tf
  main.tf
  modules/analytics/databricks_workspace/workspace.tf
  modules/azuread/applications/keyvault.tf
  modules/azuread/applications/keyvault/output.tf
  modules/azuread/applications/keyvault/variable.tf
  modules/azuread/applications/keyvault_secrets.tf
  modules/azuread/applications/variables.tf
  modules/compute/virtual_machine/examples/101-single-linux-vm/configuration.tfvars
  modules/networking/application_gateway/application_gateway.tf
  modules/networking/private-dns/module.tf
  modules/networking/private-dns/virtual_network_link.tf
  modules/networking/virtual_network/module.tf
  modules/security/keyvault/keyvault.tf
  modules/storage_account/container/output.tf
  modules/webapps/appservice/module.tf
  modules/webapps/ase/private_dns_records.tf
  modules/webapps/ase/variables.tf
  networking.tf
  networking_private_dns.tf
  networking_virtual_wan.tf
  output.tf
  variables.tf
  virtual_machines.tf
Labels: breaking-change, do not merge, enhancement

#63 Ak elasticpool to db
  examples/machine_learning/101-aml-vnet/configuration.tfvars
  examples/machine_learning/101-aml-vnet/networking_spoke.tfvars
  examples/module.tf
  examples/monitoring/service_health_alerts/configuration.tfvars
  examples/mssql_server/elastic_pools/configuration.tfvars
  examples/variables.tf
  modules/analytics/azure_machine_learning/compute_instance.tf
  modules/databases/mssql_database/database.tf
  modules/databases/mssql_database/variables.tf
  modules/databases/mssql_elastic_pool/output.tf
  modules/monitoring/service_health_alerts/service_health_alert.tf
  mssql_databases.tf
Labels: enhancement

#66 Hn aks
  aks_clusters.tf
  modules/compute/aks/diagnostics.tf
  modules/compute/aks/variables.tf
Labels: do not merge

#71 integrate appinsight to app
  .github/workflows/master-100.yaml
  aks_clusters.tf
  app_services.tf
  azurerm_application_insights.tf
  examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars
  examples/compute/virtual_machine/101-single-windows-vm/configuration.tfvars
  examples/webapps/appservice/104-appservice-appinsight/configuration.tfvars
  keyvault.tf
  main.tf
  modules/security/keyvault_access_policies/policies.tf
  modules/webapps/appservice/main.tf
  modules/webapps/appservice/module.tf
  modules/webapps/appservice/variables.tf
  modules/webapps/ase/module.tf
  storage_account_blobs.tf
Labels: bug, enhancement

#73 Hotfix for Virtual WAN peering index error
  networking_virtual_wan.tf
Labels: 0.4.1

#74 Fix - Azure AD users
  azuread.tf
  modules/azuread/users/main.tf
  modules/azuread/users/variables.tf
Labels: 0.4.1

#76 add ase to combine object for asp isolation
  .github/workflows/master-100.yaml
  app_service_environments.tf
  app_service_plans.tf
  app_services.tf
  examples/main.tf
  local.combined_objects.tf
  modules/app_insights/output.tf
  modules/webapps/appservice/main.tf
  modules/webapps/appservice/slot.tf
  modules/webapps/appservice/variables.tf
Labels: 0.4.2, enhancement

#78 Update to data_analytics components
  .devcontainer/docker-compose.yml
  .github/workflows/master-100.yaml
  examples/machine_learning/100-aml/configuration.tfvars
  examples/machine_learning/101-aml-vnet/configuration.tfvars
  examples/machine_learning/101-aml-vnet/networking_spoke.tfvars
  examples/synapse_analytics/101-synapse-sparkpool/configuration.tfvars
  machine_learning.tf
  modules/analytics/azure_machine_learning/compute_instance.tf
  modules/analytics/azure_machine_learning/compute_instance/compute_instance.tf
  modules/analytics/machine_learning/compute_instance.tf
  modules/analytics/machine_learning/compute_instance/arm_compute_instance.json
  modules/analytics/machine_learning/compute_instance/compute_instance.tf
  modules/analytics/machine_learning/compute_instance/main.tf
  modules/analytics/machine_learning/compute_instance/variables.tf
  modules/analytics/machine_learning/main.tf
  modules/analytics/machine_learning/output.tf
  modules/analytics/machine_learning/readme.md
  modules/analytics/machine_learning/variables.tf
  modules/analytics/machine_learning/workspace.tf
  synapses.tf
Labels: 0.4.2

#84 fix broken examples
  examples/mssql_server/elastic_pools/configuration.tfvars
  examples/synapse_analytics/100-synapse/configuration.tfvars
  examples/synapse_analytics/101-synapse-sparkpool/configuration.tfvars
  modules/databases/mssql_server/private_endpoints.tf
  modules/databases/mssql_server/server.tf
  modules/databases/mssql_server/variables.tf
  modules/security/keyvault_access_policies/policies.tf
  mssql_servers.tf
Labels: bug

#90 Adding missing base_tags for inheritance
  modules/compute/container_registry/private_endpoint.tf
  modules/compute/virtual_machine/network_interface.tf
  modules/databases/mssql_server/private_endpoints.tf
  modules/networking/private_endpoint/main.tf
  modules/networking/private_endpoint/private_endpoint.tf
  modules/networking/private_endpoint/variables.tf
  modules/networking/traffic_analytics/main.tf
  modules/networking/traffic_analytics/module.tf
  modules/networking/traffic_analytics/variables.tf
  modules/storage_account/private_endpoint.tf
Labels: 0.4.8, bug

#86 Adding Virtual WAN CI and #85
  .github/workflows/master-100.yaml
  examples/module.tf
  examples/networking/virtual_wan/100-vwan-multi-hubs/virtual_wan.tfvars
  examples/networking/virtual_wan/101-vwan-multi-hubs-firewalls/virtual_wan.tfvars
  examples/networking/virtual_wan/102-vwan-multi-hubs-gw/virtual_wan.tfvars
  examples/variables.tf
  modules/networking/virtual_wan/virtual_hub/azure_firewall.tf
  modules/networking/virtual_wan/virtual_hub/output.tf
Labels: 0.4.8, bug

#88 Ak kv access policies
  keyvault.tf
  modules/security/keyvault_access_policies/policies.tf
  variables.tf
Labels: bug

#92 Initial commit event hub namespaces for diagnostics
  .github/workflows/master-100.yaml
  event_hub_namespaces.tf
  examples/eventhub_namespace/100-simple-evh/configuration.tfvars
  examples/main.tf
  examples/module.tf
  examples/variables.tf
  main.tf
  modules/databases/mssql_server/server.tf
  modules/diagnostics/module.tf
  modules/event_hub_namespaces/event_hub_namespaces.tf
  modules/event_hub_namespaces/main.tf
  modules/event_hub_namespaces/output.tf
  modules/event_hub_namespaces/variables.tf
  variables.tf
Labels: 0.4.10
