Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2020-11, with the labels that each got.

#107 Update to support multiple remote user MSI
  modules/compute/virtual_machine/managed_identities.tf
  modules/compute/virtual_machine/vm_linux.tf
Labels: 0.4.13

#105 Add private module dynamic secrets
  modules/security/dynamic_keyvault_secrets/keyvault.tf
  modules/security/dynamic_keyvault_secrets/secret/keyvault_secret.tf
  modules/security/dynamic_keyvault_secrets/secret/variables.tf
  modules/security/dynamic_keyvault_secrets/secret_immutable/keyvault_secret.tf
  modules/security/dynamic_keyvault_secrets/secret_immutable/variables.tf
  modules/security/dynamic_keyvault_secrets/variables.tf
Labels: 0.4.13

#100 Enable diagnostics for NIC
  modules/automation/diagnostics.tf
  modules/compute/virtual_machine/diagnostics.tf
  modules/recovery_vault/diagnostics.tf
Labels: 0.4.13

#109 Update event_hub destination type
  modules/diagnostics/module.tf
Labels: 0.4.14

#110 0.4 route nva
  modules/networking/application_gateway/locals.networking.tf
  modules/networking/routes/module.tf
  modules/networking/routes/variables.tf
  networking.tf
Labels: 0.4.14, enhancement

#111 Azure Machine Learning Compute name collision and tags missing
  modules/analytics/machine_learning/compute_instance.tf
  modules/analytics/machine_learning/compute_instance/arm_compute_instance.json
  modules/analytics/machine_learning/compute_instance/locals.arm_parameters.tf
  modules/analytics/machine_learning/compute_instance/main.tf
  modules/analytics/machine_learning/compute_instance/variables.tf
Labels: 0.4.14

#116 Expose elastic pool as remote object
  .github/workflows/master-100.yaml
  .github/workflows/master-200.yaml
  examples/mssql_server/elastic_pools/configuration.tfvars
  locals.combined_objects.tf
  mssql_databases.tf
Labels: 0.4.15, enhancement

#101 Change Location settings in Service Health Alerts
  examples/monitoring/service_health_alerts/README.md
  examples/monitoring/service_health_alerts/configuration.tfvars
  modules/monitoring/service_health_alerts/service_health_alert.tf
  modules/monitoring/service_health_alerts/variables.tf
  monitoring.tf
Labels: 0.4.15

#123 Add slug to resources
  bastion_service.tf
  locals.tf
  modules/analytics/databricks_workspace/workspace.tf
  modules/analytics/machine_learning/compute_instance/compute_instance.tf
  modules/analytics/machine_learning/workspace.tf
  modules/analytics/synapse/spark_pool/spark_pool.tf
  modules/analytics/synapse/sql_pool/sql_pool.tf
  modules/analytics/synapse/workspace.tf
  modules/app_insights/module.tf
  modules/automation/module.tf
  modules/azuread/applications/module.tf
  modules/azuread/users/user.tf
  modules/compute/aks/aks.tf
  modules/compute/container_registry/registry.tf
  modules/compute/virtual_machine/network_interface.tf
  modules/compute/virtual_machine/vm_disk.tf
  modules/compute/virtual_machine/vm_linux.tf
  modules/compute/virtual_machine/vm_windows.tf
  modules/databases/mssql_database/database.tf
  modules/databases/mssql_elastic_pool/elastic_pool.tf
  modules/databases/mssql_server/server.tf
  modules/event_hub_namespaces/event_hub_namespaces.tf
  modules/log_analytics/workspace.tf
  modules/monitoring/service_health_alerts/service_health_alert.tf
  modules/networking/application_gateway/application_gateway.tf
  modules/networking/firewall/module.tf
  modules/networking/firewall_application_rule_collections/application_rule_collection.tf
  modules/networking/firewall_nat_rule_collections/nat_rule_collection.tf
  modules/networking/firewall_network_rule_collections/network_rule_collection.tf
  modules/networking/private-dns/virtual_network_link.tf
  modules/networking/private_endpoint/private_endpoint.tf
  modules/networking/virtual_network/module.tf
  modules/networking/virtual_network/nsg/module.tf
  modules/networking/virtual_network/subnet/subnet.tf
  modules/networking/virtual_wan/virtual_hub/azure_firewall.tf
  modules/networking/virtual_wan/virtual_hub/express_route_gateway.tf
  modules/networking/virtual_wan/virtual_hub/point_to_site_gateway.tf
  modules/networking/virtual_wan/virtual_hub/site_to_site_gateway.tf
  modules/networking/virtual_wan/virtual_hub/virtual_hub.tf
  modules/networking/virtual_wan/virtual_wan.tf
  modules/recovery_vault/recovery_vault.tf
  modules/recovery_vault/replication_policy.tf
  modules/redis_cache/module.tf
  modules/resource_group/module.tf
  modules/roles/custom_roles/module.tf
  modules/security/keyvault/keyvault.tf
  modules/security/keyvault/secrets.tf
  modules/security/managed_identity/managed_identity.tf
  modules/storage_account/storage_account.tf
  modules/webapps/appservice/module.tf
  modules/webapps/ase/module.tf
  modules/webapps/asp/module.tf
  networking.tf
Labels: 0.4.16

#121 Quick fix for Event Hub namespaces diagnostics
  modules/diagnostics/module.tf
Labels: 0.4.16, enhancement

#124 Rc elasticpool bug
  modules/databases/mssql_elastic_pool/elastic_pool.tf
  mssql_databases.tf
Labels: 0.4.16

#120 Express Route circuit and authorizations development
  .pre-commit-config.yaml
  README.md
  examples/monitoring/service_health_alerts/README.md
  examples/networking/express_routes/README.md
  examples/networking/express_routes/configuration.tfvars
  examples/networking/express_routes/standalone/main.tf
  examples/networking/express_routes/standalone/module.tf
  examples/networking/express_routes/standalone/output.tf
  examples/networking/express_routes/standalone/readme.md
  examples/networking/express_routes/standalone/variables.tf
  locals.tf
  modules/networking/express_route_circuit/express_route.tf
  modules/networking/express_route_circuit/main.tf
  modules/networking/express_route_circuit/output.tf
  modules/networking/express_route_circuit/variables.tf
  modules/networking/express_route_circuit_authorization/authorizations.tf
  modules/networking/express_route_circuit_authorization/main.tf
  modules/networking/express_route_circuit_authorization/output.tf
  modules/networking/express_route_circuit_authorization/variables.tf
  modules/webapps/ase/output.tf
  networking_express_route.tf
  variables.tf
Labels: 0.4.16, enhancement

#127 Patch - networking slug
  networking.tf
  virtual_machines.tf
Labels: bug

#129 Add diagnostics settings to Express Route Circuit
  modules/networking/express_route_circuit/diagnostics.tf
  networking_express_route.tf
Labels: 0.4.18, enhancement

#134 Adding VM backup
  .github/workflows/master-100.yaml
  README.md
  examples/README.md
  examples/compute/virtual_machine/104-single-windows-backup/configuration.tfvars
  examples/main.tf
  examples/module.tf
  examples/outputs.tf
  examples/recovery_vault/101-simple-asrv/configuration.tfvars
  examples/recovery_vault/102-asr-protection/configuration.tfvars
  examples/variables.tf
  locals.combined_objects.tf
  modules/compute/virtual_machine/backup.tf
  modules/compute/virtual_machine/variables.tf
  modules/recovery_vault/azure_recovery_fabric.tf
  modules/recovery_vault/backup_policies.tf
  modules/recovery_vault/outputs.tf
  modules/recovery_vault/protection_container.tf
  modules/recovery_vault/replication_policy.tf
  modules/storage_account/backup_container.tf
  modules/storage_account/variables.tf
  storage_accounts.tf
  virtual_machines.tf
Labels: 0.4.18, enhancement

#156 Fixing Timeout errors
  bastion_service.tf
  modules/security/keyvault/keyvault.tf
Labels: 0.4.19, bug

#162 Update for caf_foundations to define diagnostics settings at level1
  examples/keyvault/101-keyvault-policies/configuration.tfvars
  examples/keyvault/101-keyvault-policies/keyvaults.tfvars
  examples/keyvault/101-keyvault-policies/standalone/main.tf
  examples/keyvault/101-keyvault-policies/standalone/module.tf
  examples/keyvault/101-keyvault-policies/standalone/readme.md
  examples/keyvault/101-keyvault-policies/standalone/variables.tf
  locals.tf
  modules/security/keyvault/keyvault.tf
  modules/security/keyvault/private_endpoints.tf
Labels: 0.4.19

#160 Removed redundant space in terraform-azurerm-caf/modules/networking/application_gateway/variable.tf
  modules/networking/application_gateway/variable.tf
Labels: bug

#152 Add output diagnostic storage accounts
  storage_accounts.tf
Labels: 0.4.19, bug

#167 Add support for remote and local LZ for VM nic
  modules/compute/virtual_machine/network_interface.tf
Labels: 0.4.19, bug

#168 Update virtual_hub.tf
  modules/networking/virtual_wan/virtual_hub/virtual_hub.tf
Labels: 0.4.19

#169 Add NSG custom name
  .github/workflows/master-100.yaml
  examples/module.tf
  examples/networking/virtual_network/101-vnet-peering-nsg/configuration.tfvars
  examples/networking/virtual_network/101-vnet-peering-nsg/network_security_group_definition.tfvars
  examples/networking/virtual_network/101-vnet-peering-nsg/peering.tfvars
  examples/networking/virtual_network/101-vnet-peering-nsg/virtual_networks.tfvars
  examples/variables.tf
  examples/vm_extensions.tf
  modules/networking/virtual_network/nsg/module.tf
Labels: 0.4.19

#172 increase asp timeout
  modules/webapps/asp/module.tf
Labels: enhancement

#171 Virtual Network Gateway Connection
  .github/workflows/master-100.yaml
  bastion_service.tf
  examples/module.tf
  examples/networking/virtual_network_gateway/configuration.tfvars
  examples/networking/virtual_network_gateway_connections/configuration.tfvars
  examples/variables.tf
  locals.tf
  log_analytics.tf
  modules/networking/virtual_network_gateway_connections/main.tf
  modules/networking/virtual_network_gateway_connections/module.tf
  modules/networking/virtual_network_gateway_connections/output.tf
  modules/networking/virtual_network_gateway_connections/variables.tf
  modules/networking/virtual_network_gateways/main.tf
  modules/networking/virtual_network_gateways/module.tf
  modules/networking/virtual_network_gateways/output.tf
  modules/networking/virtual_network_gateways/variables.tf
  networking_vngw.tf
  variables.tf
Labels: 0.4.19, new submodule

#173 NSG Flow logs
  examples/module.tf
  examples/networking/virtual_network/200-nsg-flow-logs/configuration.tfvars
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/networking/network_watcher/main.tf
  modules/networking/network_watcher/module.tf
  modules/networking/network_watcher/output.tf
  modules/networking/network_watcher/variables.tf
  modules/networking/traffic_analytics/module.tf
  modules/networking/traffic_analytics/output.tf
  modules/networking/traffic_analytics/variables.tf
  modules/networking/virtual_network/nsg/flow_logs/flow_logs.tf
  modules/networking/virtual_network/nsg/flow_logs/variables.tf
  modules/networking/virtual_network/nsg/nsg_flow_logs.tf
  modules/networking/virtual_network/nsg/variables.tf
  modules/networking/virtual_network/variables.tf
  networking.tf
  variables.tf
Labels: 0.4.19
