Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2020-12, with the labels that each got.

#176 Fix for in-vm diagnostics - support diagnostics destinations
  .devcontainer/docker-compose.yml
  .github/workflows/master-100.yaml
  examples/compute/virtual_machine/104-single-windows-backup/configuration.tfvars
  examples/compute/virtual_machine/210-vm-bastion-winrm/standalone/module.tf
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/standalone/main.tf
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/standalone/module.tf
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/standalone/readme.md
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/standalone/variables.tf
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/standalone/vm_extensions.tf
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/virtual_machines.tfvars
  examples/keyvault/101-keyvault-policies/keyvaults.tfvars
  examples/keyvault/101-keyvault-policies/standalone/module.tf
  examples/main.tf
  examples/recovery_vault/101-simple-asrv/configuration.tfvars
  examples/variables.tf
  examples/vm_extensions.tf
  modules/compute/virtual_machine/backup.tf
  modules/compute/virtual_machine_extensions/Microsoft.EnterpriseCloud.Monitoring.tf
  modules/compute/virtual_machine_extensions/microsoft.azure.diagnostics.tf
  modules/log_analytics/output.tf
  modules/security/keyvault/keyvault.tf
  virtual_machines.tf
Labels: 0.4.19, bug

#187 Fix private endpoint resource group
  modules/recovery_vault/backup_policies_file_share.tf
  modules/recovery_vault/backup_policies_vm.tf
  modules/recovery_vault/main.tf
  modules/recovery_vault/private_endpoints.tf
Labels: bug

#186 Akeloth kvci
  .github/workflows/master-100.yaml
  container_registry.tf
  diagnostics.tf
  event_hub_namespaces.tf
  examples/keyvault/102-keyvault-cert-issuer/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  keyvault_certificate_issuers.tf
  modules/security/keyvault/examples/102-with-networking/variables.tf
  modules/security/keyvault_certificate_issuer/cert_issuer.tf
  modules/security/keyvault_certificate_issuer/main.tf
  modules/security/keyvault_certificate_issuer/output.tf
  modules/security/keyvault_certificate_issuer/variables.tf
  variables.tf
  virtual_machines.tf
Labels: 0.4.20

#196 fix force replacement issue in elastic pool
  modules/databases/mssql_elastic_pool/elastic_pool.tf
  modules/databases/mssql_elastic_pool/variables.tf
  mssql_elastic_pools.tf
Labels: 0.4.21, bug

#197 Fix compute ci - change location
  .github/workflows/master-100.yaml
  UPGRADE.md
  dynamic_secrets.tf
  examples/compute/availability_set/100-simple-availabilityset/configuration.tfvars
  examples/compute/availability_set/101-availabilityset-with-proximity-placement-group/configuration.tfvars
  examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/configuration.tfvars
  examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/standalone/module.tf
  examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/standalone/readme.md
  examples/compute/virtual_machine/210-vm-bastion-winrm/standalone/module.tf
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/configuration.tfvars
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/keyvaults.tfvars
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/standalone/module.tf
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/standalone/readme.md
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/standalone/variables.tf
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/standalone/vm_extensions.tf
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/virtual_machines.tfvars
  examples/dynamic_secrets.tf
  examples/keyvault/101-keyvault-policies/configuration.tfvars
  examples/keyvault/101-keyvault-policies/standalone/readme.md
  examples/locals.remote_tfstates.tf
  examples/module.tf
  examples/networking/private_links/endpoints/centralized/configuration.tfvars
  keyvault_certificate_issuers.tf
  modules/compute/virtual_machine/keyvault.tf
  modules/compute/virtual_machine/output.tf
  modules/compute/virtual_machine/vm_linux.tf
  modules/compute/virtual_machine/vm_windows.tf
  modules/compute/virtual_machine/vm_windows_winrm_self.tf
  modules/security/dynamic_keyvault_secrets/keyvault.tf
  modules/security/dynamic_keyvault_secrets/secret_purge.tf
  modules/security/dynamic_keyvault_secrets/variables.tf
  modules/security/keyvault_certificate_issuer/cert_issuer.tf
  modules/security/keyvault_certificate_issuer/variables.tf
Labels: 0.4.21, breaking-change

#188 Add support for VPN type in Virtual Network Gateway
  .devcontainer/docker-compose.yml
  .github/workflows/master-100.yaml
  diagnostics.tf
  dynamic_secrets.tf
  event_hub_namespaces.tf
  examples/app_gateway/210-agw-with-keyvault/certificates.tfvars
  examples/app_gateway/210-agw-with-keyvault/standalone/readme.md
  examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/standalone/readme.md
  examples/compute/virtual_machine/210-vm-bastion-winrm/standalone/readme.md
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/standalone/readme.md
  examples/cosmos_db/100-simple-cosmos-db-mongo/mongodb_databases.tfvars
  examples/cosmos_db/100-simple-cosmos-db-sql/sql_databases.tfvars
  examples/eventhub_namespace/101-evh-with-private-endpoint/configuration.tfvars
  examples/keyvault/101-keyvault-policies/standalone/readme.md
  examples/keyvault/102-keyvault-cert-issuer/configuration.tfvars
  examples/locals.remote_tfstates.tf
  examples/module.tf
  examples/mssql_mi/200-mi-two-regions/nsg.tfvars
  examples/mssql_mi/200-mi/nsg.tfvars
  examples/mssql_mi/standalone/module.tf
  examples/mssql_mi/standalone/readme.md
  examples/mssql_server/200-mssql-two-regions.tfvars
  examples/networking/private_links/endpoints/centralized/private_endpoints.tfvars
  examples/networking/private_links/endpoints/centralized/standalone/module.tf
  examples/networking/private_links/endpoints/centralized/standalone/private_endpoints.tfvars
  examples/networking/virtual_network_gateway/100-expressroute-gateway/configuration.tfvars
  examples/networking/virtual_network_gateway/101-vpn-site-to-site/configuration.tfvars
  examples/networking/virtual_network_gateway/102-vpn-site-to-site-active-active/configuration.tfvars
  examples/networking/virtual_network_gateway/103-vpn-site-to-site-connection/configuration.tfvars
  examples/networking/virtual_network_gateway_connections/100-expressroute-gateway-connection/configuration.tfvars
  examples/variables.tf
  keyvault_certificate_issuers.tf
  locals.tf
  modules/compute/virtual_machine_extensions/Microsoft.EnterpriseCloud.Monitoring.tf
  modules/databases/cosmos_db/mongo_database/mongo_database.tf
  modules/databases/cosmos_db/sql_database/sql_database.tf
  modules/monitoring/service_health_alerts/alert-servicehealth.json
  modules/networking/local_network_gateways/main.tf
  modules/networking/local_network_gateways/module.tf
  modules/networking/local_network_gateways/output.tf
  modules/networking/local_network_gateways/variables.tf
  modules/networking/virtual_network_gateway_connections/module.tf
  modules/networking/virtual_network_gateway_connections/variables.tf
  modules/networking/virtual_network_gateways/module.tf
  modules/security/keyvault_certificate_issuer/cert_issuer.tf
  mssql_elastic_pools.tf
  networking_vngw.tf
  variables.tf
Labels: enhancement

#207 Patch - VM Windows - Get username and password from keyvault key in remote subscription
  modules/compute/virtual_machine/vm_windows.tf
Labels: bug

#211 Back to SEA
  .github/workflows/master-100.yaml
  examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/configuration.tfvars
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/configuration.tfvars
  examples/keyvault/101-keyvault-policies/configuration.tfvars
  examples/networking/private_links/endpoints/centralized/configuration.tfvars
Labels: CI

#210 akloth roles
  examples/networking/front_door/100-simple-front_door/dns_zone.tfvars
  roles.tf
Labels: 4.21.2

#209 Add privatelink for mssql servers
  examples/networking/private_links/endpoints/centralized/mssql_servers.tfvars
  examples/networking/private_links/endpoints/centralized/private_dns.tfvars
  examples/networking/private_links/endpoints/centralized/private_endpoints.tfvars
  modules/networking/private_links/endpoints/subnet/mssql_servers.tf
  networking_private_links.tf
Labels: 4.21.2, enhancement

#148 Adding PostgreSQL
  .github/workflows/master-100.yaml
  examples/module.tf
  examples/postgresql_server/100-simple-postgresql/configuration.tfvars
  examples/postgresql_server/101-vnet-rule-postgresql/configuration.tfvars
  examples/postgresql_server/102-private-endpoint-postgresql/configuration.tfvars
  examples/postgresql_server/103-private-endpoint-with-fw-rule/configuration.tfvars
  examples/variables.tf
  keyvault_certificate_requests.tf
  locals.combined_objects.tf
  locals.tf
  modules/databases/postgresql_server/auditing.tf
  modules/databases/postgresql_server/configuration.tf
  modules/databases/postgresql_server/database.tf
  modules/databases/postgresql_server/firewall_rule.tf
  modules/databases/postgresql_server/main.tf
  modules/databases/postgresql_server/network_rule.tf
  modules/databases/postgresql_server/output.tf
  modules/databases/postgresql_server/private_endpoint.tf
  modules/databases/postgresql_server/server.tf
  modules/databases/postgresql_server/threat_detection.tf
  modules/databases/postgresql_server/variables.tf
  postgresql_servers.tf
  roles.tf
  variables.tf
Labels: new submodule

#155 Adding MySQL
  .github/workflows/master-100.yaml
  examples/locals.remote_tfstates.tf
  examples/module.tf
  examples/mysql_server/100-simple-mysql/configuration.tfvars
  examples/mysql_server/101-vnet-rule-mysql/configuration.tfvars
  examples/mysql_server/102-private-endpoint-mysql/configuration.tfvars
  examples/mysql_server/103-private-endpoint-with-fw-rule-mysql/configuration.tfvars
  examples/networking/private_links/endpoints/centralized/keyvaults.tfvars
  examples/networking/private_links/endpoints/centralized/mysql_servers.tfvars
  examples/networking/private_links/endpoints/centralized/private_endpoints.tfvars
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/databases/mysql_server/audit.tf
  modules/databases/mysql_server/configuration.tf
  modules/databases/mysql_server/database.tf
  modules/databases/mysql_server/diagnostics.tf
  modules/databases/mysql_server/firewall_rule.tf
  modules/databases/mysql_server/main.tf
  modules/databases/mysql_server/network_rule.tf
  modules/databases/mysql_server/output.tf
  modules/databases/mysql_server/private_endpoints.tf
  modules/databases/mysql_server/server.tf
  modules/databases/mysql_server/threat_detection.tf
  modules/databases/mysql_server/variables.tf
  modules/networking/private_links/endpoints/subnet/mysql_servers.tf
  mysql_servers.tf
  networking_private_links.tf
  roles.tf
Labels: new submodule

#161 Adding MariaDB
  .github/workflows/master-100.yaml
  examples/mariadb_server/100-simple-mariadb/configuration.tfvars
  examples/mariadb_server/101-vnet-rule-mariadb/configuration.tfvars
  examples/mariadb_server/102-private-endpoint-mariadb/configuration.tfvars
  examples/mariadb_server/103-private-endpoint-with-fw-rule-mariadb/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  locals.tf
  mariadb_servers.tf
  modules/databases/mariadb_server/audit.tf
  modules/databases/mariadb_server/configuration.tf
  modules/databases/mariadb_server/database.tf
  modules/databases/mariadb_server/diagnostics.tf
  modules/databases/mariadb_server/firewall_rule.tf
  modules/databases/mariadb_server/main.tf
  modules/databases/mariadb_server/network_rule.tf
  modules/databases/mariadb_server/output.tf
  modules/databases/mariadb_server/private_endpoints.tf
  modules/databases/mariadb_server/server.tf
  modules/databases/mariadb_server/threat_detection.tf
  modules/databases/mariadb_server/variables.tf
Labels: new submodule
