Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2021-11, with the labels that each got.

#767 Add virtual subnets outside of virtual networks object
  .github/workflows/standalone-scenarios.json
  examples/module.tf
  examples/networking/virtual_subnets/100-simple-subnet-rbac/configuration.tfvars
  examples/networking/virtual_subnets/100-simple-subnet-rbac/nsg.tfvars
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/networking/virtual_network/module.tf
  modules/networking/virtual_network/output.tf
  networking.tf
  roles.tf
Labels: new submodule

#777 Update storage container and subscription lifecycle
  modules/storage_container/main.tf
  modules/storage_container/module.tf
  modules/storage_container/output.tf
  modules/storage_container/variables.tf
  modules/subscriptions/subscriptions.tf
  storage_container.tf
Labels: bug

#778 #766 Front Door Advanced Config
  .github/workflows/standalone-scenarios.json
  data_factory.tf
  examples/module.tf
  examples/networking/front_door/102-front_door_advanced/configuration.tfvars
  examples/networking/front_door/102-front_door_advanced/diagnostic_storage_accounts.tfvars
  examples/networking/front_door/102-front_door_advanced/diagnostics_definition.tfvars
  examples/networking/front_door/102-front_door_advanced/diagnostics_destinations.tfvars
  examples/networking/front_door/102-front_door_advanced/dns_zone.tfvars
  examples/networking/front_door/102-front_door_advanced/front_door_advanced.tfvars
  examples/networking/front_door/102-front_door_advanced/front_door_waf_policies.tfvars
  examples/networking/front_door/102-front_door_advanced/front_doors.tfvars
  examples/networking/front_door/102-front_door_advanced/keyvault.tfvars
  examples/networking/front_door/102-front_door_advanced/keyvault_certificate_requests.tfvars
  examples/variables.tf
  front_doors.tf
  locals.combined_objects.tf
  locals.tf
  modules/networking/front_door/output.tf
  modules/networking/frontdoor_custom_https_configuration/README.md
  modules/networking/frontdoor_custom_https_configuration/main.tf
  modules/networking/frontdoor_custom_https_configuration/module.tf
  modules/networking/frontdoor_custom_https_configuration/output.tf
  modules/networking/frontdoor_custom_https_configuration/variables.tf
  modules/networking/frontdoor_rules_engine/README.md
  modules/networking/frontdoor_rules_engine/main.tf
  modules/networking/frontdoor_rules_engine/module.tf
  modules/networking/frontdoor_rules_engine/output.tf
  modules/networking/frontdoor_rules_engine/variables.tf
Labels: enhancement

#698 Update AKS up to AzureRM 2.81.0
  .github/workflows/standalone-scenarios.json
  aks_clusters.tf
  examples/compute/kubernetes_services/201-agic/agw.tfvars
  examples/compute/kubernetes_services/201-agic/aks.tfvars
  examples/compute/kubernetes_services/201-agic/diagnostics.tfvars
  examples/compute/kubernetes_services/201-agic/networking.tfvars
  examples/outputs.tf
  modules/compute/aks/aks.tf
  modules/compute/aks/variables.tf
Labels: enhancement, aks

#774 Enable DDOS plan from other LZs
  locals.combined_objects.tf
  networking.tf
Labels: bug

#773 Update output.tf
  modules/databases/mssql_database/output.tf
Labels: enhancement

#780 Adding Data Factory runtimes
  .github/workflows/standalone-scenarios.json
  data_factory.tf
  examples/data_factory/112-data_factory_integration_runtime_azure_ssis/configuration.tfvars
  examples/data_factory/113-data_factory_integration_runtime_azure_ssis_mssql_server/configuration.tfvars
  examples/data_factory/114-data_factory_integration_runtime_self_hosted/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/data_factory/data_factory_integration_runtime_azure_ssis/main.tf
  modules/data_factory/data_factory_integration_runtime_azure_ssis/module.tf
  modules/data_factory/data_factory_integration_runtime_azure_ssis/output.tf
  modules/data_factory/data_factory_integration_runtime_azure_ssis/variables.tf
  modules/data_factory/data_factory_integration_runtime_self_hosted/README.md
  modules/data_factory/data_factory_integration_runtime_self_hosted/main.tf
  modules/data_factory/data_factory_integration_runtime_self_hosted/module.tf
  modules/data_factory/data_factory_integration_runtime_self_hosted/output.tf
  modules/data_factory/data_factory_integration_runtime_self_hosted/variables.tf
  modules/databases/mssql_server/server.tf
Labels: new submodule

#785 Sm data factory linked service azure databricks
  modules/data_factory/linked_services/azure_databricks/module.tf
Labels: enhancement

#783 Add private dns ids + resources
  examples/networking/private_links/endpoints/centralized/private_endpoints.tfvars
  modules/networking/private_endpoint/private_endpoint.tf
  networking_private_links.tf
Labels: enhancement

#786 Update load balancer options
  modules/networking/load_balancers/load_balancers.tf
Labels: enhancement

#796 Data Factory SSIS examples
  data_factory.tf
  examples/data_factory/112-data_factory_integration_runtime_azure_ssis/configuration.tfvars
  modules/data_factory/data_factory_integration_runtime_self_hosted/output.tf
Labels: bug

#795 Fix Specify a pre-existing Log Analytics repository for diagnostics d…
  examples/diagnostics_profiles/202-reuse-existing-log-analytics/configuration.tfvars
  examples/diagnostics_profiles/202-reuse-existing-log-analytics/diagnostics_definition.tfvars
  examples/diagnostics_profiles/202-reuse-existing-log-analytics/diagnostics_destinations.tfvars
  examples/diagnostics_profiles/202-reuse-existing-log-analytics/log_analytics.tfvars
  examples/diagnostics_profiles/202-reuse-existing-log-analytics/virtual_network.tfvars
  modules/diagnostics/module.tf
Labels: bug

#789 Availability Set Lifecycle
  modules/compute/virtual_machine/vm_linux.tf
  modules/compute/virtual_machine/vm_windows.tf
Labels: bug

#790 Machine Learning Compute Instance
  .github/workflows/standalone-scenarios.json
  examples/machine_learning/102-aml-compute_instance/README.md
  examples/machine_learning/102-aml-compute_instance/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  locals.tf
  machine_learning.tf
  modules/analytics/machine_learning_compute_instance/main.tf
  modules/analytics/machine_learning_compute_instance/module.tf
  modules/analytics/machine_learning_compute_instance/output.tf
  modules/analytics/machine_learning_compute_instance/variables.tf
Labels: enhancement

#799 Fix for Specify a pre-existing Backup Vault and policy for virtual ma…
  examples/compute/virtual_machine/104-single-windows-backup-existing/configuration.tfvars
  modules/compute/virtual_machine/backup.tf
Labels: bug

#787 Remote ASG in VMSS, added timezone, license_type to windows vmss
  modules/compute/virtual_machine_scale_set/main.tf
  modules/compute/virtual_machine_scale_set/vmss_windows.tf
Labels: bug

#814 Include supprt to pre existing subnet
  examples/compute/kubernetes_services/101-single-cluster/aks.tfvars
  examples/compute/virtual_machine_scale_set/100-linux-win-vmss-lb/configuration.tfvars
  examples/mssql_server/111-sqlserver_private_endpoint/configurations.tfvars
  modules/compute/virtual_machine_scale_set/vmss_linux.tf
  modules/compute/virtual_machine_scale_set/vmss_windows.tf
  modules/databases/mssql_server/private_endpoints.tf
  modules/databases/mssql_server/server.tf
Labels: enhancement

#806 Storage remote subnet
  examples/storage_accounts/103-storage-account-network-rules/configuration.tfvars
  modules/storage_account/storage_account.tf
Labels: enhancement

#760 Adding virtual machine custom script extension
  examples/compute/virtual_machine/110-single-windows-vm-custom-script-extension/configuration.tfvars
  examples/compute/virtual_machine/110-single-windows-vm-custom-script-extension/helloworld.ps1
  examples/vm_extensions.tf
  modules/compute/virtual_machine_extensions/custom_script.tf
  modules/compute/virtual_machine_extensions/variables.tf
Labels: enhancement

#816 Application Gateway v1 enhancement
  application_gateway_applications.tf
  locals.combined_objects.tf
  modules/networking/application_gateway_application/backend_pool.tf
  modules/networking/application_gateway_application/http_listener.tf
  modules/networking/application_gateway_application/http_settings.tf
  modules/networking/application_gateway_application/probe.tf
  modules/networking/application_gateway_application/request_routing_rule.tf
  modules/networking/application_gateway_application/root_cert.tf
  modules/networking/application_gateway_application/scripts/delete_resource.sh
  modules/networking/application_gateway_application/scripts/set_resource.sh
  modules/networking/application_gateway_application/ssl_cert.tf
  modules/networking/application_gateway_application/url_path_map.tf
  modules/networking/application_gateway_application/url_path_rule.tf
Labels: bug

#817 Improving Azure Machine Learning compute instances
  .github/workflows/standalone-scenarios.json
  examples/machine_learning/102-aml-compute_instance/README.md
  examples/machine_learning/102-aml-compute_instance/configuration.tfvars
  examples/machine_learning/103-aml-compute_instance_assing-to-user/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  locals.tf
  machine_learning.tf
  modules/analytics/machine_learning_compute_instance/main.tf
  modules/analytics/machine_learning_compute_instance/managed_identities.tf
  modules/analytics/machine_learning_compute_instance/module.tf
  modules/analytics/machine_learning_compute_instance/output.tf
  modules/analytics/machine_learning_compute_instance/variables.tf
Labels: enhancement

#824 Fix to #814
  modules/compute/virtual_machine_scale_set/vmss_linux.tf
  modules/compute/virtual_machine_scale_set/vmss_windows.tf
Labels: bug

#823 Application Gateway and Azure Functions to use pre-existing vnet and subnet
  .github/workflows/standalone-scenarios.json
  UPGRADE.md
  application_gateways.tf
  examples/app_gateway/100-simple-app-gateway/configuration.tfvars
  examples/module.tf
  examples/role_mapping/100-simple-role-mapping/configuration.tfvars
  examples/variables.tf
  examples/webapps/function_app/101-function_app-private/configuration.tfvars
  examples/webapps/function_app/102-function_app-linux/configuration.tfvars
  examples/webapps/function_app/README.md
  function_app.tf
  modules/networking/application_gateway/locals.networking.tf
  modules/webapps/function_app/module.tf
  modules/webapps/function_app/variables.tf
Labels: enhancement

#805 Add MCA support for subscriptions
  modules/subscriptions/subscriptions.tf
  modules/subscriptions/variables.tf
Labels: enhancement

#827 #800 Recovery Vault Managed Identity
  modules/recovery_vault/outputs.tf
Labels: enhancement

#826 Replace template_file provider with templatefile()
  examples/shared_image_gallery/101-packer_service_principal/packer.tfvars
  modules/shared_image_gallery/packer_service_principal/packer.tf
Labels: enhancement

#832 Adding dependecies for each subcomponent of agw_applications
  modules/networking/application_gateway_application/probe.tf
  modules/networking/application_gateway_application/url_path_map.tf
  modules/networking/application_gateway_application/url_path_rule.tf
Labels: enhancement

#833 Inject pre-existing subnet SQL MI and ACR
  examples/compute/container_registry/200-acr-private-link/configuration.tfvars
  modules/compute/container_registry/private_endpoint.tf
  modules/compute/container_registry/registry.tf
  msssql_managed_instances.tf
Labels: enhancement
