Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2021-12, with the labels that each got.

#839 Make subnets attribute optional in AKS and to fix service_cidr error
  aks_clusters.tf
  modules/compute/aks/aks.tf
Labels: bug

#842 Update AADDS to support replica sets
  .github/workflows/standalone-scenarios.json
  active_directory_domain_service.tf
  examples/identity/active_directory_domain_service/100-active_directory_domain_service-replica/configuration.tfvars
  examples/identity/active_directory_domain_service/100-active_directory_domain_service-replica/nsg.tfvars
  examples/identity/active_directory_domain_service/100-active_directory_domain_service-replica/vnets.tfvars
  modules/identity/active_directory_domain_service/module.tf
  modules/identity/active_directory_domain_service/output.tf
  modules/identity/active_directory_domain_service_replica_set/main.tf
  modules/identity/active_directory_domain_service_replica_set/module.tf
  modules/identity/active_directory_domain_service_replica_set/output.tf
  modules/identity/active_directory_domain_service_replica_set/variables.tf
Labels: new submodule

#840 Backport Application Gateway Ingress Controller
  .devcontainer/docker-compose.yml
  .github/workflows/master-standalone-tf100-longrunners.yaml
  .github/workflows/master-standalone-tf100.yaml
  .github/workflows/standalone-scenarios.json
  .vscode/settings.json
  aks_clusters.tf
  application_gateway_platforms.tf
  examples/compute/kubernetes_services/201-agic-brownfield/agw_platform.tfvars
  examples/compute/kubernetes_services/201-agic-brownfield/aks.tfvars
  examples/compute/kubernetes_services/201-agic-brownfield/certificates.tfvars
  examples/compute/kubernetes_services/201-agic-brownfield/diagnostics.tfvars
  examples/compute/kubernetes_services/201-agic-brownfield/keyvault.tfvars
  examples/compute/kubernetes_services/201-agic-brownfield/networking.tfvars
  examples/compute/kubernetes_services/201-agic-brownfield/public_ip.tfvars
  examples/compute/kubernetes_services/201-agic-brownfield/role_mapping.tfvars
  examples/outputs.tf
  modules/compute/aks/aks.tf
  modules/compute/aks/examples/104-private-cluster/keyvault.tfvars
  modules/compute/aks/output.tf
  modules/compute/aks/variables.tf
  modules/networking/application_gateway_platform/application_gateway.tf
  modules/networking/application_gateway_platform/locals.networking.tf
  modules/networking/application_gateway_platform/variable.tf
  roles.tf
  rover_on_ssh_host.yml
Labels: enhancement

#843 Private dns vnet link - Added support to reference remote vnet
  modules/networking/private-dns/virtual_network_link.tf
Labels: enhancement

#846 Fix issue in Application Gateway v1 URL path map rule on delete null resource
  examples/app_gateway/301-agw-v1/agw_application.tfvars
  modules/networking/application_gateway_application/url_path_rule.tf
Labels: bug

#807 Add support for vmss custom script and domain join extensions
  .github/workflows/standalone-scenarios.json
  examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
  examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/scripts/helloworld.ps1
  examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/scripts/helloworld.sh
  examples/compute/virtual_machine_scale_set/103-linux-win-vmss-domain-join-extension/configuration.tfvars
  examples/vmss_extensions.tf
  modules/compute/virtual_machine_scale_set_extensions/custom_script.tf
  modules/compute/virtual_machine_scale_set_extensions/domain_join.tf
  modules/compute/virtual_machine_scale_set_extensions/variables.tf
Labels: enhancement, do not merge

#803 Add monitor_autoscale_setting(s) module
  .github/workflows/standalone-scenarios.json
  examples/compute/virtual_machine_scale_set/104-linux-win-vmss-as-lb/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  locals.tf
  modules/monitoring/monitor_autoscale_settings/main.tf
  modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
  modules/monitoring/monitor_autoscale_settings/variables.tf
  monitor_autoscale_settings.tf
Labels: do not merge, new submodule

#757 Service bus Module
  .github/workflows/standalone-scenarios.json
  examples/module.tf
  examples/servicebus/100-servicebus-simple/configuration.tfvars
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/servicebus/namespace/main.tf
  modules/servicebus/namespace/namespace.tf
  modules/servicebus/namespace/namespace_auth_rule.tf
  modules/servicebus/namespace/namespace_auth_rule/main.tf
  modules/servicebus/namespace/namespace_auth_rule/namespace_auth_rule.tf
  modules/servicebus/namespace/namespace_auth_rule/output.tf
  modules/servicebus/namespace/namespace_auth_rule/variables.tf
  modules/servicebus/namespace/namespace_network_rule_sets.tf
  modules/servicebus/namespace/network_rule_set/main.tf
  modules/servicebus/namespace/network_rule_set/network_rule_set.tf
  modules/servicebus/namespace/network_rule_set/output.tf
  modules/servicebus/namespace/network_rule_set/variables.tf
  modules/servicebus/namespace/output.tf
  modules/servicebus/namespace/variables.tf
  modules/servicebus/queue/main.tf
  modules/servicebus/queue/output.tf
  modules/servicebus/queue/queue.tf
  modules/servicebus/queue/queue_auth_rule/main.tf
  modules/servicebus/queue/queue_auth_rule/output.tf
  modules/servicebus/queue/queue_auth_rule/queue_auth_rule.tf
  modules/servicebus/queue/queue_auth_rule/variables.tf
  modules/servicebus/queue/variables.tf
  modules/servicebus/topic/main.tf
  modules/servicebus/topic/output.tf
  modules/servicebus/topic/subscription/main.tf
  modules/servicebus/topic/subscription/output.tf
  modules/servicebus/topic/subscription/subscription.tf
  modules/servicebus/topic/subscription/subscription_rule/correlation_filter/correlation_filter.tf
  modules/servicebus/topic/subscription/subscription_rule/correlation_filter/main.tf
  modules/servicebus/topic/subscription/subscription_rule/correlation_filter/output.tf
  modules/servicebus/topic/subscription/subscription_rule/correlation_filter/variables.tf
  modules/servicebus/topic/subscription/subscription_rule/sql_filter/main.tf
  modules/servicebus/topic/subscription/subscription_rule/sql_filter/output.tf
  modules/servicebus/topic/subscription/subscription_rule/sql_filter/sql_filter.tf
  modules/servicebus/topic/subscription/subscription_rule/sql_filter/variables.tf
  modules/servicebus/topic/subscription/subscription_rules.tf
  modules/servicebus/topic/subscription/variables.tf
  modules/servicebus/topic/subscriptions.tf
  modules/servicebus/topic/topic.tf
  modules/servicebus/topic/topic_auth_rule/main.tf
  modules/servicebus/topic/topic_auth_rule/output.tf
  modules/servicebus/topic/topic_auth_rule/topic_auth_rule.tf
  modules/servicebus/topic/topic_auth_rule/variables.tf
  modules/servicebus/topic/variables.tf
  servicebus_namespaces.tf
  servicebus_queues.tf
  servicebus_topics.tf
  variables.tf
Labels: new submodule

#848 Private Endpoint - AzureBackup Vault
  examples/recovery_vault/104-backupvault-with-private-endpoint/configuration.tfvars
  examples/recovery_vault/104-backupvault-with-private-endpoint/private_dns.tfvars
  examples/recovery_vault/104-backupvault-with-private-endpoint/private_endpoints.tfvars
  examples/recovery_vault/104-backupvault-with-private-endpoint/recovery_vaults.tfvars
  examples/recovery_vault/104-backupvault-with-private-endpoint/role_mapping.tfvars
  examples/recovery_vault/104-backupvault-with-private-endpoint/virtual_networks.tfvars
  modules/networking/private_links/endpoints/subnet/recovery_vaults.tf
Labels: enhancement

#808 Adding Azure CDN
  .github/workflows/standalone-scenarios.json
  cdn.tf
  examples/module.tf
  examples/networking/cdn/100-simple-cdn/configuration.tfvars
  examples/networking/cdn/100-simple-cdn/profiles.tfvars
  examples/networking/cdn/100-simple-cdn/storage_accounts.tfvars
  examples/networking/cdn/README.md
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/networking/cdn_endpoint/main.tf
  modules/networking/cdn_endpoint/module.tf
  modules/networking/cdn_endpoint/output.tf
  modules/networking/cdn_endpoint/variables.tf
  modules/networking/cdn_profile/diagnostics.tf
  modules/networking/cdn_profile/main.tf
  modules/networking/cdn_profile/module.tf
  modules/networking/cdn_profile/output.tf
  modules/networking/cdn_profile/variables.tf
  modules/storage_account/output.tf
Labels: new submodule

#850 Final vmss custom script extension fixes
  examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
  modules/compute/virtual_machine_scale_set_extensions/custom_script.tf
Labels: enhancement

#853 add try null wrapper to servicebus_queues and service_bus_topics
  modules/servicebus/topic/subscriptions.tf
  servicebus_queues.tf
  servicebus_topics.tf
Labels: bug

#879 Existing Key Vault for AppGW
  examples/app_gateway/210-agw-with-keyvault/application.tfvars
  modules/networking/application_gateway/application_gateway.tf
Labels: enhancement
