Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2021-09, with the labels that each got.

#643 Update Output.tf files with "sensitive = true"
  modules/app_insights/output.tf
  modules/networking/express_route_circuit/output.tf
  modules/networking/express_route_circuit_authorization/output.tf
  networking_express_route.tf
Labels: bug

#662 Update databricks for azurerm 2.74.0
  .github/workflows/standalone-scenarios.json
  databricks.tf
  examples/databricks/100-simple-databricks/configuration.tfvars
  examples/databricks/100-standard-databricks-no-vnet/configuration.tfvars
  examples/databricks/101-standard-databricks-vnet/configuration.tfvars
  examples/databricks/102-premium-aml/configuration.tfvars
  modules/analytics/databricks_workspace/diagnostics.tf
  modules/analytics/databricks_workspace/variables.tf
  modules/analytics/databricks_workspace/workspace.tf
Labels: enhancement

#665 FIx AKS autoscale
  modules/compute/aks/aks.tf
Labels: enhancement

#659 Add support for Redis private endpoint
  examples/networking/private_links/endpoints/centralized/private_endpoints.tfvars
  examples/networking/private_links/endpoints/centralized/redis_caches.tfvars
  locals.combined_objects.tf
  modules/networking/private_links/endpoints/subnet/redis_cache.tf
  networking_private_links.tf
Labels: enhancement, do not merge

#673 Create alias to an existing subscription
  modules/subscriptions/subscriptions.tf
Labels: bug

#636 Support remote rg lz referencing
  examples/storage_accounts/100-simple-storage-account-blob-container/configuration.tfvars
  storage_accounts.tf
  virtual_machines.tf
Labels: enhancement

#671 Add support for adding virtual-network-links outside of private-dns-zone creation
  examples/networking/private_dns_vnet_link/100_pvtdns_vnetlink/configuration.tfvars
  locals.tf
  modules/networking/private_dns_vnet_link/main.tf
  modules/networking/private_dns_vnet_link/module.tf
  modules/networking/private_dns_vnet_link/output.tf
  modules/networking/private_dns_vnet_link/variables.tf
  networking_private_dns.tf
Labels: enhancement

#677 Add Owner to Azuread group
  modules/azuread/groups/group.tf
Labels: enhancement

#676 Support IDS in policy
  examples/networking/firewall/103-firewall-policies/configuration.tfvars
  modules/networking/firewall_policies/firewall_policy.tf
Labels: enhancement

#675 Support for bring your own NIC in VM
  examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars
  modules/compute/virtual_machine/application_security_group.tf
  modules/compute/virtual_machine/diagnostics.tf
  modules/compute/virtual_machine/network_interface.tf
  modules/compute/virtual_machine/output.tf
Labels: enhancement

#674 Fix typo azurermfw vnet
  examples/networking/virtual_network/100-simple-vnet-subnets-nsgs/configuration.tfvars
  networking.tf
Labels: bug

#679 Input resource id for privatelink
  examples/networking/private_links/endpoints/centralized/private_endpoints.tfvars
  modules/networking/private_links/endpoints/subnet/diagnostic_event_hub_namespaces.tf
  modules/networking/private_links/endpoints/subnet/diagnostic_storage_accounts.tf
  modules/networking/private_links/endpoints/subnet/eventhub_namespaces.tf
  modules/networking/private_links/endpoints/subnet/keyvaults.tf
  modules/networking/private_links/endpoints/subnet/mssql_servers.tf
  modules/networking/private_links/endpoints/subnet/mysql_servers.tf
  modules/networking/private_links/endpoints/subnet/recovery_vaults.tf
  modules/networking/private_links/endpoints/subnet/redis_cache.tf
  modules/networking/private_links/endpoints/subnet/storage_accounts.tf
  networking_private_links.tf
Labels: enhancement

#680 Support remote KeyVault for MSSQL or MySQL
  examples/mysql_server/102-private-endpoint-mysql/configuration.tfvars
  mssql_servers.tf
  msssql_managed_instances.tf
  mysql_servers.tf
Labels: enhancement

#681 update ACR to support public access flag
  container_registry.tf
  examples/compute/container_registry/200-acr-vnet/configuration.tfvars
  modules/compute/container_registry/registry.tf
  modules/compute/container_registry/variables.tf
Labels: enhancement

#678 add support for azure ad group membership for managed identities
  .github/workflows/standalone-scenarios.json
  azuread_groups.tf
  examples/azuread/104-azuread-group-membership/configuration.tfvars
  modules/azuread/groups_members/azuread_groups_membership.tf
  modules/azuread/groups_members/membership/membership.tf
  modules/azuread/groups_members/membership/variables.tf
  modules/azuread/groups_members/variables.tf
Labels: enhancement

#689 [Feature] RSV VM backup policy to add instant_restore_retention_days support and example
  examples/recovery_vault/101-simple-asrv/configuration.tfvars
  modules/recovery_vault/backup_policies_vm.tf
Labels: enhancement

#688 Allow legacy method for VM creation with data disk at boot time
  examples/compute/virtual_machine/109-legacy-vm-creation/configuration.tfvars
  modules/compute/virtual_machine/main.tf
  modules/compute/virtual_machine/vm_legacy.tf
  modules/compute/virtual_machine/vm_linux.tf
  modules/compute/virtual_machine/vm_windows.tf
  modules/compute/virtual_machine/vm_windows_winrm_self.tf
Labels: enhancement

#694 Update the lun value
  modules/compute/virtual_machine/vm_legacy.tf
Labels: bug

#702 VM Datadisk add lifecycle to ignore
  modules/compute/virtual_machine/vm_disk.tf
Labels: enhancement
