Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2021-01, with the labels that each got.

#219 Refactoring cosmos mongo api for hierarchy
  examples/cosmos_db/100-simple-cosmos-db-mongo/mongodb_databases.tfvars
  examples/cosmos_db/100-simple-cosmos-db-mongo/standalone/main.tf
  examples/cosmos_db/100-simple-cosmos-db-mongo/standalone/module.tf
  modules/databases/cosmos_db/mongo_database.tf
  modules/databases/cosmos_db/mongo_database/mongo_collection/main.tf
  modules/databases/cosmos_db/mongo_database/mongo_collection/mongo_collection.tf
  modules/databases/cosmos_db/mongo_database/mongo_collection/variables.tf
  modules/databases/cosmos_db/mongo_database/mongo_database.tf
  modules/databases/cosmos_db/mongo_database/output.tf
  modules/databases/cosmos_db/mongo_database/variables.tf
Labels: enhancement

#230 Hn aks addons
  aks_clusters.tf
  examples/compute/kubernetes_services/101-single-cluster/aks.tfvars
  examples/compute/kubernetes_services/101-single-cluster/diagnostics.tfvars
  examples/compute/kubernetes_services/101-single-cluster/standalone/ci.sh
  examples/compute/kubernetes_services/101-single-cluster/standalone/module.tf
  examples/compute/kubernetes_services/101-single-cluster/standalone/output.tf
  examples/compute/kubernetes_services/101-single-cluster/standalone/readme.md
  examples/compute/kubernetes_services/101-single-cluster/standalone/variables.tf
  examples/compute/kubernetes_services/102-multi-nodepools/diagnostics.tfvars
  examples/compute/kubernetes_services/102-multi-nodepools/standalone/ci.sh
  examples/compute/kubernetes_services/102-multi-nodepools/standalone/module.tf
  examples/compute/kubernetes_services/102-multi-nodepools/standalone/output.tf
  examples/compute/kubernetes_services/102-multi-nodepools/standalone/readme.md
  examples/compute/kubernetes_services/102-multi-nodepools/standalone/variables.tf
  examples/compute/kubernetes_services/103-multi-clusters/diagnostics.tfvars
  examples/compute/kubernetes_services/103-multi-clusters/standalone/module.tf
  examples/compute/kubernetes_services/103-multi-clusters/standalone/readme.md
  examples/compute/kubernetes_services/104-private-cluster/diagnostics.tfvars
  examples/compute/kubernetes_services/104-private-cluster/standalone/module.tf
  examples/compute/kubernetes_services/104-private-cluster/standalone/readme.md
  modules/compute/aks/aks.tf
  modules/compute/aks/variables.tf
Labels: enhancement

#235 Adding first implementation for Azure Netapp Files and NFSv3
  .github/workflows/master-100.yaml
  .github/workflows/master-standalone.yaml
  aks_clusters.tf
  examples/README.md
  examples/automation/100-simple-automation-account/standalone/module.tf
  examples/module.tf
  examples/netapp/101-nfs/configuration.tfvars
  examples/netapp/101-nfs/standalone/main.tf
  examples/netapp/101-nfs/standalone/module.tf
  examples/netapp/101-nfs/standalone/output.tf
  examples/netapp/101-nfs/standalone/readme.md
  examples/netapp/101-nfs/standalone/variables.tf
  examples/outputs.tf
  examples/variables.tf
  locals.tf
  modules/netapp/account.tf
  modules/netapp/main.tf
  modules/netapp/output.tf
  modules/netapp/pool/output.tf
  modules/netapp/pool/pool.tf
  modules/netapp/pool/variables.tf
  modules/netapp/pools.tf
  modules/netapp/variables.tf
  modules/netapp/volume/output.tf
  modules/netapp/volume/variables.tf
  modules/netapp/volume/volume.tf
  msssql_managed_instances.tf
  netapp.tf
  variables.tf
Labels: new submodule

#240 dns_zones - add public ip alias record
  examples/networking/dns_zones/100-simple-dns_zone/configuration.tfvars
  examples/networking/dns_zones/100-simple-dns_zone/dns_zone_records.tfvars
  examples/networking/dns_zones/100-simple-dns_zone/dns_zones.tfvars
  examples/networking/dns_zones/100-simple-dns_zone/public_ip_addresses.tfvars
  examples/networking/dns_zones/100-simple-dns_zone/standalone/module.tf
  examples/networking/dns_zones/100-simple-dns_zone/standalone/readme.md
  examples/networking/dns_zones/100-simple-dns_zone/standalone/variables.tf
  modules/networking/dns_zone/records.tf
  modules/networking/dns_zone/records/output.tf
  modules/networking/dns_zone/records/record_a.tf
  modules/networking/dns_zone/records/variables.tf
  modules/networking/dns_zone/variables.tf
  networking_dns_zones.tf
Labels: 5.1.0, enhancement
