Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2021-05, with the labels that each got.

#424 Add SQL Database Name to Outputs
  modules/databases/mssql_database/output.tf
Labels: enhancement

#420 Fix ip_rules and bypass arguments for storage accounts
  examples/storage_accounts/103-storage-account-network-rules/configuration.tfvars
  modules/storage_account/storage_account.tf
Labels: bug

#418 VM: Adding external network objects reference by ID
  examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars
  modules/compute/virtual_machine/network_interface.tf
Labels: enhancement

#404 Add support for Redis Cache VNET integration
  .github/workflows/master-100-testcases.json
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  examples/redis_cache/102-redis-private/README.md
  examples/redis_cache/102-redis-private/configuration.tfvars
  modules/redis_cache/module.tf
  modules/redis_cache/variables.tf
  redis_caches.tf
Labels: enhancement

#425 Add support for Redis Cache VNET integration
  .github/workflows/master-100-testcases.json
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  examples/redis_cache/102-redis-private/README.md
  examples/redis_cache/102-redis-private/configuration.tfvars
  modules/redis_cache/module.tf
  modules/redis_cache/variables.tf
  redis_caches.tf
Labels: enhancement

#408 Add support for Function App VNET integration
  .github/workflows/master-100-testcases.json
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  examples/webapps/function_app/101-function_app-private/configuration.tfvars
  function_app.tf
  modules/webapps/function_app/module.tf
  modules/webapps/function_app/variables.tf
Labels: enhancement

#406 Add support for AppService VNET integration
  .github/workflows/master-100-testcases.json
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  app_services.tf
  examples/webapps/appservice/107-appservice-private/configuration.tfvars
  modules/webapps/appservice/module.tf
  modules/webapps/appservice/variables.tf
Labels: enhancement

#423 Add SQL Server and DB to Dynamic App Settings
  locals.tf
Labels: bug

#428 Fix SQLDB Module MSI user creation
  modules/databases/mssql_database/db_permissions.tf
  modules/databases/mssql_database/scripts/set_db_permissions.sh
  modules/databases/mssql_database/scripts/set_db_permissions.sql
Labels: bug

#431 Fix aks node pool subnet
  modules/compute/aks/aks.tf
Labels: bug

#426 Add support for Function App VNET integration
  .github/workflows/master-100-testcases.json
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  examples/webapps/function_app/101-function_app-private/configuration.tfvars
  function_app.tf
  modules/webapps/function_app/module.tf
  modules/webapps/function_app/variables.tf
Labels: enhancement

#434 Adding references to local.resource_groups for resource group reuse feature
  container_registry.tf
  diagnostics.tf
  disk_encryption_sets.tf
  keyvault.tf
  log_analytics.tf
  mariadb_servers.tf
  mssql_servers.tf
  mysql_servers.tf
  networking_express_route.tf
  networking_private_links.tf
  networking_virtual_wan.tf
  postgresql_servers.tf
  recovery_vaults.tf
  storage_accounts.tf
Labels: bug

#433 Decouple keyvault access policy for keyvault lz_key and azuread_app lz_key
  modules/security/keyvault_access_policies/policies.tf
Labels: enhancement

#435 rover updates
  .devcontainer/docker-compose.yml
  .github/workflows/master-sql-mi-tf13.yaml
  .github/workflows/master-sql-mi-tf14.yaml
  .github/workflows/master-sql-mi-tf15.yaml
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
Labels: enhancement

#436 Fix threat_intelligence_mode
  modules/networking/firewall_policies/firewall_policy.tf
Labels: bug

#442 Fix submap for Appservice VNET integration
  app_services.tf
  examples/webapps/appservice/107-appservice-private/configuration.tfvars
Labels: enhancement

#445 Fix naming issue for NSGs
  modules/networking/network_security_group/module.tf
Labels: bug

#446 Add Mssql server firewall network rule and firewall rule support
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  examples/mssql_server/109-sqlserver-network-firewall-rule/configurations.tfvars
  modules/databases/mssql_server/server.tf
Labels: enhancement

#443 Add support for managed boot diagnostics on VMs, etc. #368
  examples/compute/availability_set/100-simple-availabilityset/configuration.tfvars
  examples/compute/availability_set/101-availabilityset-with-proximity-placement-group/configuration.tfvars
  examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars
  examples/compute/virtual_machine/101-single-windows-vm/configuration.tfvars
  examples/compute/virtual_machine/104-single-windows-backup/configuration.tfvars
  examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/configuration.tfvars
  examples/compute/virtual_machine/210-vm-bastion-winrm/virtual_machines.tfvars
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/virtual_machines.tfvars
  modules/compute/virtual_machine/variables.tf
  modules/compute/virtual_machine/vm_linux.tf
  modules/compute/virtual_machine/vm_windows.tf
  virtual_machines.tf
Labels: enhancement

#444 Added support to add UDRs to special subnets
  examples/networking/virtual_network/102-simple-vnet-special-subnet-udr/configuration.tfvars
  examples/networking/virtual_network/102-simple-vnet-special-subnet-udr/nsg.tfvars
  examples/networking/virtual_network/102-simple-vnet-special-subnet-udr/public-ip-addresses.tfvars
  examples/networking/virtual_network/102-simple-vnet-special-subnet-udr/routes.tfvars
  modules/networking/virtual_network/module.tf
Labels: enhancement

#383 Updated the MangementLock Code
  examples/storage_accounts/102-storage-account-advanced-options/configuration.tfvars
  examples/storage_accounts/102-storage-account-advanced-options/standalone/module.tf
  examples/storage_accounts/102-storage-account-advanced-options/standalone/variables.tf
  locals.tf
  modules/security/management_locks/main.tf
  modules/security/management_locks/management_lock.tf
  modules/security/management_locks/variables.tf
  variables.tf
Labels: do not merge

#447 Integration - Add support for managed boot diagnostics on VMs, etc. #368
  examples/compute/availability_set/100-simple-availabilityset/configuration.tfvars
  examples/compute/availability_set/101-availabilityset-with-proximity-placement-group/configuration.tfvars
  examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars
  examples/compute/virtual_machine/101-single-windows-vm/configuration.tfvars
  examples/compute/virtual_machine/104-single-windows-backup/configuration.tfvars
  examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/configuration.tfvars
  examples/compute/virtual_machine/210-vm-bastion-winrm/virtual_machines.tfvars
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/virtual_machines.tfvars
  modules/compute/virtual_machine/variables.tf
  modules/compute/virtual_machine/vm_linux.tf
  modules/compute/virtual_machine/vm_windows.tf
  virtual_machines.tf
Labels: enhancement

#448 Integration - Added support to add UDRs to special subnets #444
  examples/networking/virtual_network/102-simple-vnet-special-subnet-udr/configuration.tfvars
  examples/networking/virtual_network/102-simple-vnet-special-subnet-udr/nsg.tfvars
  examples/networking/virtual_network/102-simple-vnet-special-subnet-udr/public-ip-addresses.tfvars
  examples/networking/virtual_network/102-simple-vnet-special-subnet-udr/routes.tfvars
  modules/networking/virtual_network/module.tf
Labels: enhancement

#450 Updating rover and fixing purge bug
  .devcontainer/docker-compose.yml
  .github/workflows/master-sql-mi-tf13.yaml
  .github/workflows/master-sql-mi-tf14.yaml
  .github/workflows/master-sql-mi-tf15.yaml
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
Labels: CI, bug

#427 Integration -Add support for AppService VNET integration
  .github/workflows/master-100-testcases.json
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  app_services.tf
  examples/webapps/appservice/107-appservice-private/configuration.tfvars
  modules/webapps/appservice/module.tf
  modules/webapps/appservice/variables.tf
Labels: enhancement

#457 Fix Load Balancer rule
  examples/networking/load_balancers/101-load-balancer-with-rules/configuration.tfvars
  modules/networking/load_balancers/load_balancers.tf
Labels: bug

#458 Updating the NSG code - Fixed the NSG duplication issue for Version 1 NSGs
  modules/networking/virtual_network/module.tf
  modules/networking/virtual_network/nsg/diagnostics.tf
  modules/networking/virtual_network/nsg/module.tf
  modules/networking/virtual_network/nsg/nsg_flow_logs.tf
  modules/networking/virtual_network/nsg/variables.tf
  modules/networking/virtual_network/variables.tf
  network_security_groups.tf
  networking.tf
Labels: bug

#465 Added 'plan' block for Linux VMs
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  examples/compute/virtual_machine/106-marketplace-image-with-plan/configuration.tfvars
  modules/compute/virtual_machine/vm_linux.tf
Labels: enhancement

#440 Gap analysis - analytics module
  locals.combined_objects.tf
  machine_learning.tf
  main.tf
  modules/analytics/databricks_workspace/workspace.tf
  modules/analytics/machine_learning/variables.tf
  modules/analytics/machine_learning/workspace.tf
  modules/analytics/synapse/spark_pool/spark_pool.tf
  modules/analytics/synapse/workspace.tf
  modules/compute/container_registry/registry.tf
  modules/networking/front_door/front_door.tf
Labels: enhancement

#456 Add sovereign cloud endpoints and suffix environment variables (part 3)
  landingzones/caf_example/module.tf
  landingzones/caf_example/variables.tf
  locals.tf
  modules/databases/mssql_database/main.tf
  modules/databases/mssql_database/variables.tf
  mssql_databases.tf
  variables.tf
Labels: enhancement

#469 Patch firewall policy
  examples/networking/virtual_wan/105-vwan-hub-route-table/virtual_wan.tfvars
  modules/networking/firewall_policies/firewall_policy.tf
  modules/networking/virtual_hub_er_gateway_connection/arm_vhub_er_connection.json
  modules/networking/virtual_hub_er_gateway_connection/er_connection.tf
  modules/networking/virtual_hub_er_gateway_connection/variables.tf
  modules/networking/virtual_hub_route_tables/hub_route_tables.json
  modules/networking/virtual_hub_route_tables/route_local.tf
  modules/networking/virtual_hub_route_tables/route_table.tf
  modules/networking/virtual_hub_route_tables/route_table_arm.tf
  modules/networking/virtual_hub_route_tables/route_table_sh.tf
  modules/networking/virtual_hub_route_tables/scripts/hub_route_table.sh
  modules/networking/virtual_hub_route_tables/variables.tf
  modules/networking/virtual_wan/virtual_hub/azure_firewall.tf
  modules/networking/virtual_wan/virtual_hub/express_route_gateway.tf
  modules/networking/virtual_wan/virtual_hub/output.tf
  modules/networking/virtual_wan/virtual_hub/point_to_site_gateway.tf
  modules/networking/virtual_wan/virtual_hub/site_to_site_gateway.tf
  modules/networking/virtual_wan/virtual_wan.tf
  networking_virtual_hub_connection.tf
  networking_virtual_hub_er_connection.tf
  networking_virtual_hub_peering_tables.tf
  networking_virtual_hub_route_table.tf
Labels: bug, enhancement

#479 Patch vhub route tables
  main.tf
  modules/networking/virtual_hub_er_gateway_connection/arm_vhub_er_connection.json
  modules/networking/virtual_hub_er_gateway_connection/er_connection.tf
Labels: bug
