Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2021-06, with the labels that each got.

#481 Fix json format
  modules/networking/virtual_hub_er_gateway_connection/arm_vhub_er_connection.json
Labels: bug

#489 null check added for fqdn
  modules/networking/application_gateway/application_gateway.tf
  modules/networking/application_gateway/locals.backend_pools.tf
Labels: enhancement

#492 Updated remaining hardcoded Azure urls
  modules/azuread/applications/scripts/grant_consent.sh
  modules/azuread/roles/scripts/set_ad_role.sh
  modules/subscription_billing_role_assignment/billing_role_assignment.tf
  modules/subscription_billing_role_assignment/role_assignment/billing_role_assignment.tf
  modules/subscription_billing_role_assignment/role_assignment/variables.tf
  modules/subscription_billing_role_assignment/variables.tf
  modules/subscriptions/scripts/assign_subscription_to_mg.sh
  modules/subscriptions/scripts/tags.sh
  subscriptions.tf
Labels: enhancement

#496 Adding null check Application Gateway FQDN
  modules/networking/application_gateway/application_gateway.tf
  modules/networking/application_gateway/locals.backend_pools.tf
Labels: enhancement

#483 Error on subscription creation with Azure AD Application service principal
  modules/subscriptions/scripts/refresh_access_token.sh
Labels: enhancement

#486 Separate virtual_hubs deployments from virtual_wans
  landingzones/caf_example/module.tf
  landingzones/caf_example/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/networking/virtual_wan/virtual_hub/site_to_site_gateway.tf
  networking_virtual_hub_connection.tf
  networking_virtual_hub_er_connection.tf
  networking_virtual_hub_route_table.tf
  networking_virtual_hubs.tf
Labels: enhancement

#497 Fix example 105
  networking_virtual_hub_route_table.tf
Labels: bug

#500 [BUG] Script is missing a "/" in path
  modules/azuread/applications/scripts/grant_consent.sh
Labels: bug

#503 Create Virtual Hub peering by vnet resource id
  networking_virtual_hub_connection.tf
Labels: enhancement

#504 Updated local.combined_objects_azurerm_firewalls each.value iterator
  networking.tf
Labels: bug

#485 Add VMSS Module
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars
  examples/compute/virtual_machine_scale_set/100-linux-win-vmss-lb/configuration.tfvars
  examples/compute/virtual_machine_scale_set/101-linux-win-vmss-agw/configuration.tfvars
  landingzones/caf_example/module.tf
  landingzones/caf_example/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/compute/virtual_machine_scale_set/keyvault.tf
  modules/compute/virtual_machine_scale_set/main.tf
  modules/compute/virtual_machine_scale_set/managed_identities.tf
  modules/compute/virtual_machine_scale_set/output.tf
  modules/compute/virtual_machine_scale_set/variables.tf
  modules/compute/virtual_machine_scale_set/vmss_linux.tf
  modules/compute/virtual_machine_scale_set/vmss_windows.tf
  modules/compute/virtual_machine_scale_set/vmss_windows_winrm_self.tf
  modules/networking/application_gateway/locals.backend_pools.tf
  modules/networking/application_gateway/output.tf
  modules/networking/load_balancers/output.tf
  virtual_machines_scale_sets.tf
Labels: new submodule

#508 Add Random_String Implementation
  .pre-commit-config.yaml
  examples/random_string/configuration.tfvars
  modules/random_string/main.tf
  modules/random_string/module.tf
  modules/random_string/output.tf
  modules/random_string/variables.tf
  networking_virtual_hub_route_table.tf
  random_string.tf
  variables.tf
Labels: new submodule

#509 Add Application Gateway ssl_policy
  modules/networking/application_gateway/application_gateway.tf
  modules/networking/application_gateway/locals.backend_pools.tf
Labels: enhancement

#520 Patch routes for backward compatibility
  networking.tf
Labels: bug

#515 Support for VM extension multi subscription mode
  modules/compute/virtual_machine_extensions/Microsoft.EnterpriseCloud.Monitoring.tf
  modules/compute/virtual_machine_extensions/microsoft.azure.diagnostics.tf
Labels: bug

#511 Refactor aks subnets to take in a dictionary of key(s) and resource id
  modules/compute/aks/aks.tf
Labels: enhancement, integration-branch-to-test

#518 Add support for vpn_sites and vpn_gateway_connections
  examples/networking/virtual_wan/108-vwan-vpn-site/virtual_wan.tfvars
  examples/networking/virtual_wan/109-vwan-vpn-gateway-connection/virtual_wan.tfvars
  landingzones/caf_example/README.md
  landingzones/caf_example/module.tf
  landingzones/caf_example/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/networking/application_gateway/locals.backend_pools.tf
  modules/networking/virtual_wan/virtual_hub/site_to_site_gateway.tf
  modules/networking/vpn_gateway_connection/main.tf
  modules/networking/vpn_gateway_connection/module.tf
  modules/networking/vpn_gateway_connection/output.tf
  modules/networking/vpn_gateway_connection/variables.tf
  modules/networking/vpn_site/main.tf
  modules/networking/vpn_site/module.tf
  modules/networking/vpn_site/output.tf
  modules/networking/vpn_site/variables.tf
  networking_vpn_gateway_connection.tf
  networking_vpn_site.tf
Labels: integration-branch-to-test, new submodule

#523 Add support for vpn_sites and vpn_gateway_connections #518
  .devcontainer/devcontainer.json
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  examples/compute/virtual_machine/106-marketplace-image-with-plan/configuration.tfvars
  examples/compute/virtual_machine_scale_set/100-linux-win-vmss-lb/configuration.tfvars
  examples/compute/virtual_machine_scale_set/101-linux-win-vmss-agw/configuration.tfvars
  examples/networking/virtual_wan/108-vwan-vpn-site/virtual_wan.tfvars
  examples/networking/virtual_wan/109-vwan-vpn-gateway-connection/virtual_wan.tfvars
  landingzones/caf_example/README.md
  landingzones/caf_example/module.tf
  landingzones/caf_example/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/networking/application_gateway/locals.backend_pools.tf
  modules/networking/virtual_wan/virtual_hub/site_to_site_gateway.tf
  modules/networking/vpn_gateway_connection/main.tf
  modules/networking/vpn_gateway_connection/module.tf
  modules/networking/vpn_gateway_connection/output.tf
  modules/networking/vpn_gateway_connection/variables.tf
  modules/networking/vpn_site/main.tf
  modules/networking/vpn_site/module.tf
  modules/networking/vpn_site/output.tf
  modules/networking/vpn_site/variables.tf
  networking_vpn_gateway_connection.tf
  networking_vpn_site.tf
Labels: new submodule

#524 Add support for dedicated host groups
  dedicated_hosts.tf
  examples/compute/dedicated_hosts/101-dedicated-host/configuration.tfvars
  examples/compute/dedicated_hosts/102-dedicated-host-vms/configuration.tfvars
  examples/compute/dedicated_hosts/102-dedicated-host-vms/vm.tfvars
  landingzones/caf_example/module.tf
  landingzones/caf_example/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/compute/aks/aks.tf
  modules/compute/dedicated_host_groups/main.tf
  modules/compute/dedicated_host_groups/module.tf
  modules/compute/dedicated_host_groups/output.tf
  modules/compute/dedicated_host_groups/variables.tf
  modules/compute/dedicated_hosts/main.tf
  modules/compute/dedicated_hosts/module.tf
  modules/compute/dedicated_hosts/output.tf
  modules/compute/dedicated_hosts/variables.tf
  modules/compute/virtual_machine/variables.tf
  modules/compute/virtual_machine/vm_linux.tf
  modules/compute/virtual_machine/vm_windows.tf
  modules/compute/virtual_machine_extensions/Microsoft.EnterpriseCloud.Monitoring.tf
  modules/compute/virtual_machine_extensions/microsoft.azure.diagnostics.tf
  networking.tf
  virtual_machines.tf
Labels: new submodule

#532 Bugfix for vpn connection remote objects
  networking_vpn_gateway_connection.tf
Labels: bug

#534 Add remote firewall policy to rule_collection_groups
  modules/networking/firewall_policy_rule_collection_groups/firewall_policy_rule_collection_groups.tf
  modules/networking/firewall_policy_rule_collection_groups/variables.tf
  networking_firewall.tf
Labels: enhancement

#536 Fix output for subscriptions
  locals.combined_objects.tf
  roles.tf
Labels: bug

#538 Add module for Azure Storage Queue
  examples/storage_account_queues/101-storage-account-queue/configuration.tfvars
  locals.tf
  modules/storage_account/output.tf
  modules/storage_account/queue/output.tf
  modules/storage_account/queue/queue.tf
  modules/storage_account/queue/variables.tf
  modules/storage_account/storage_account.tf
  storage_account_queues.tf
Labels: enhancement

#547 Fix admin consent
  modules/azuread/applications/scripts/grant_consent.sh
  modules/azuread/applications_v1/api_permissions.tf
  modules/azuread/applications_v1/scripts/grant_consent.sh
  modules/azuread/service_principal/grant_api_permissions.tf
  modules/azuread/service_principal/scripts/grant_consent.sh
Labels: bug

#551 Patch.azuread
  azuread_credentials.tf
  azuread_service_principals.tf
  modules/azuread/applications/scripts/grant_consent.sh
  modules/azuread/credentials/password.tf
  modules/azuread/credentials/password_rotation.tf
  modules/azuread/credentials/variables.tf
  modules/azuread/service_principal/module.tf
  modules/azuread/service_principal/scripts/grant_consent.sh
  modules/security/keyvault_access_policies/access_policy/access_policy.tf
Labels: enhancement

#549 Review Event Hub logic and configurations
  .github/workflows/standalone-scenarios.json
  examples/eventhub/102-namespace-and-evh-with-auth-rules/configuration.tfvars
  examples/eventhub/104-namespace-and-evh-with-storage/configuration.tfvars
  modules/event_hubs/consumer_groups/consumer_groups.tf
  modules/event_hubs/consumer_groups/output.tf
  modules/event_hubs/consumer_groups/variables.tf
  modules/event_hubs/hubs/auth_rules/auth_rules.tf
  modules/event_hubs/hubs/event_hub.tf
  modules/event_hubs/hubs/output.tf
  modules/event_hubs/hubs/variables.tf
Labels: enhancement

#542 Feature/remote rg selected resources
  application_gateways.tf
  examples/compute/virtual_machine/106-marketplace-image-with-plan/configuration.tfvars
  examples/compute/virtual_machine_scale_set/100-linux-win-vmss-lb/configuration.tfvars
  examples/compute/virtual_machine_scale_set/101-linux-win-vmss-agw/configuration.tfvars
  keyvault.tf
  keyvault_certificate_issuers.tf
  load_balancers.tf
  networking.tf
  virtual_machines.tf
  virtual_machines_scale_sets.tf
Labels: enhancement

#545 Add support for msi random suffix
  examples/compute/virtual_machine/106-marketplace-image-with-plan/configuration.tfvars
  examples/compute/virtual_machine_scale_set/100-linux-win-vmss-lb/configuration.tfvars
  examples/compute/virtual_machine_scale_set/101-linux-win-vmss-agw/configuration.tfvars
  modules/security/managed_identity/managed_identity.tf
Labels: enhancement

#553 Fix grant consent from user in vscode
  modules/azuread/applications/scripts/grant_consent.sh
  modules/azuread/service_principal/scripts/grant_consent.sh
Labels: bug
