Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2021-03, with the labels that each got.

#303 update aad apps password key to prevent cycle error
  modules/azuread/applications/keyvault_secrets.tf
  modules/azuread/applications/module.tf
Labels: bug

#318 added back basetags output for keyvault
  modules/security/keyvault/output.tf
Labels: bug

#316 Name composition update for #306
  documentation/conventions.md
  modules/compute/container_group/container_group.tf
  modules/networking/front_door/front_door.tf
  modules/networking/load_balancers/load_balancers.tf
Labels: bug

#313 Adding azure devops project creation capabilities to CAF
  azure_devops_projects.tf
  examples/README.md
  examples/devops/providers/azure-devops/new_project/ado_project.tfvars
  examples/devops/providers/azure-devops/new_project/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  modules/devops/providers/azure-devops/README.md
  modules/devops/providers/azure-devops/main.tf
  modules/devops/providers/azure-devops/output.tf
  modules/devops/providers/azure-devops/project.tf
  modules/devops/providers/azure-devops/variables.tf
  variables.tf
Labels: new submodule

#326 Shared Image Gallery
  .github/workflows/master-100.yaml
  examples/module.tf
  examples/scripts/cloud-init/install-ansible-packer.config
  examples/shared_image_gallery/101-packer_service_principal/destroy_image.sh
  examples/shared_image_gallery/101-packer_service_principal/image_gallery.tfvars
  examples/shared_image_gallery/101-packer_service_principal/keyvaults.tfvars
  examples/shared_image_gallery/101-packer_service_principal/packer.tfvars
  examples/shared_image_gallery/101-packer_service_principal/packer_files/ansible-ping.yml
  examples/shared_image_gallery/101-packer_service_principal/packer_files/packer_template_service_principal.json
  examples/shared_image_gallery/101-packer_service_principal/packer_files/packer_template_sp.json
  examples/shared_image_gallery/101-packer_service_principal/role_mapping.tfvars
  examples/shared_image_gallery/101-packer_service_principal/service_principal.tfvars
  examples/variables.tf
  locals.tf
  modules/azuread/applications/output.tf
  modules/compute/virtual_machine_extensions/Microsoft.EnterpriseCloud.Monitoring.tf
  modules/compute/virtual_machine_extensions/microsoft.azure.diagnostics.tf
  modules/shared_image_gallery/image_definitions/Image_definitions.tf
  modules/shared_image_gallery/image_definitions/main.tf
  modules/shared_image_gallery/image_definitions/output.tf
  modules/shared_image_gallery/image_definitions/variables.tf
  modules/shared_image_gallery/image_galleries/main.tf
  modules/shared_image_gallery/image_galleries/output.tf
  modules/shared_image_gallery/image_galleries/shared_image_gallery.tf
  modules/shared_image_gallery/image_galleries/variables.tf
  modules/shared_image_gallery/packer_service_principal/destroy_image.sh
  modules/shared_image_gallery/packer_service_principal/main.tf
  modules/shared_image_gallery/packer_service_principal/packer.tf
  modules/shared_image_gallery/packer_service_principal/variables.tf
  roles.tf
  shared_image_gallery.tf
  variables.tf
Labels: new submodule

#293 added source_image_id support for linux/windows vm
  modules/compute/virtual_machine/variables.tf
  modules/compute/virtual_machine/vm_linux.tf
  modules/compute/virtual_machine/vm_windows.tf
Labels: enhancement

#329 Adding NSG module with NIC association
  examples/compute/virtual_machine/210-vm-bastion-winrm/configuration.tfvars
  examples/compute/virtual_machine/210-vm-bastion-winrm/nsg_definitions.tfvars
  examples/compute/virtual_machine/210-vm-bastion-winrm/virtual_machines.tfvars
  modules/compute/virtual_machine/network_interface.tf
  modules/compute/virtual_machine/variables.tf
  modules/networking/network_security_group/diagnostics.tf
  modules/networking/network_security_group/main.tf
  modules/networking/network_security_group/module.tf
  modules/networking/network_security_group/variables.tf
  network_security_groups.tf
  virtual_machines.tf
Labels: enhancement

#335 Network Interface Card association to Load Balancer
  .github/workflows/master-standalone.yaml
  examples/networking/load_balancers/103-load-balancer-nic-association/configuration.tfvars
  examples/networking/load_balancers/103-load-balancer-nic-association/standalone/ci.sh
  examples/networking/load_balancers/103-load-balancer-nic-association/standalone/main.tf
  examples/networking/load_balancers/103-load-balancer-nic-association/standalone/module.tf
  examples/networking/load_balancers/103-load-balancer-nic-association/standalone/readme.md
  examples/networking/load_balancers/103-load-balancer-nic-association/standalone/variables.tf
  load_balancers.tf
  modules/compute/virtual_machine/output.tf
  modules/networking/load_balancers/load_balancers.tf
  modules/networking/load_balancers/variables.tf
Labels: enhancement

#339 Enhance sqldb module to create db user for managed identity
  aks_clusters.tf
  azuread_roles.tf
  modules/databases/mssql_database/db_permissions.tf
  modules/databases/mssql_database/main.tf
  modules/databases/mssql_database/scripts/set_db_permissions.sh
  modules/databases/mssql_database/scripts/set_db_permissions.sql
  modules/databases/mssql_database/variables.tf
  modules/security/managed_identity/output.tf
  mssql_databases.tf
  sudo
Labels: enhancement

#341 Override base tags with local definitions
  modules/compute/virtual_machine/vm_windows_winrm_self.tf
  modules/databases/cosmos_dbs/cassandra_keyspace/main.tf
  modules/databases/cosmos_dbs/gremlin_database/gremlin_graph/main.tf
  modules/databases/cosmos_dbs/gremlin_database/main.tf
  modules/databases/cosmos_dbs/mongo_database/main.tf
  modules/databases/cosmos_dbs/mongo_database/mongo_collection/main.tf
  modules/databases/cosmos_dbs/sql_database/main.tf
  modules/databases/cosmos_dbs/table/main.tf
  modules/databases/mssql_managed_database/main.tf
  modules/databases/mssql_managed_instance/main.tf
  modules/event_hubs/consumer_groups/main.tf
  modules/event_hubs/hubs/auth_rules/main.tf
  modules/event_hubs/namespaces/auth_rules/main.tf
  modules/event_hubs/namespaces/main.tf
  modules/networking/dns_zone/main.tf
  modules/networking/dns_zone/records/record_a.tf
  modules/networking/dns_zone/records/record_aaaa.tf
  modules/networking/dns_zone/records/record_caa.tf
  modules/networking/dns_zone/records/record_cname.tf
  modules/networking/dns_zone/records/record_mx.tf
  modules/networking/dns_zone/records/record_ns.tf
  modules/networking/dns_zone/records/record_ptr.tf
  modules/networking/dns_zone/records/record_srv.tf
  modules/networking/dns_zone/records/record_txt.tf
  modules/networking/domain_name_registrations/main.tf
  modules/networking/load_balancers/main.tf
  modules/security/keyvault/keyvault.tf
  modules/security/keyvault/private_endpoints.tf
  modules/shared_image_gallery/image_definitions/main.tf
  modules/shared_image_gallery/image_galleries/main.tf
  modules/shared_image_gallery/packer_service_principal/main.tf
  modules/storage_account/storage_account.tf
  modules/webapps/ase/main.tf
Labels: bug

#342 Fix eventhub diagnostics profiles
  .github/workflows/master-standalone-tf13.yaml
  examples/diagnostics_profiles/200-diagnostics-eventhub-namespaces/configuration.tfvars
  examples/diagnostics_profiles/200-diagnostics-eventhub-namespaces/diagnostic_event_hub_namespaces.tfvars
  examples/diagnostics_profiles/200-diagnostics-eventhub-namespaces/diagnostics_definition.tfvars
  examples/diagnostics_profiles/200-diagnostics-eventhub-namespaces/diagnostics_destinations.tfvars
  examples/diagnostics_profiles/200-diagnostics-eventhub-namespaces/standalone/ci.sh
  examples/diagnostics_profiles/200-diagnostics-eventhub-namespaces/standalone/main.tf
  examples/diagnostics_profiles/200-diagnostics-eventhub-namespaces/standalone/module.tf
  examples/diagnostics_profiles/200-diagnostics-eventhub-namespaces/standalone/readme.md
  examples/diagnostics_profiles/200-diagnostics-eventhub-namespaces/standalone/variables.tf
  modules/diagnostics/module.tf
Labels: bug

#333 Adding NSG module with NIC association
  examples/app_gateway/210-agw-with-keyvault/standalone/variables.tf
  examples/compute/virtual_machine/101-single-windows-vm/standalone/variables.tf
  examples/compute/virtual_machine/102-single-vm-data-disks/standalone/variables.tf
  examples/compute/virtual_machine/104-single-windows-backup/standalone/variables.tf
  examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/standalone/variables.tf
  examples/compute/virtual_machine/210-vm-bastion-winrm/configuration.tfvars
  examples/compute/virtual_machine/210-vm-bastion-winrm/nsg_definitions.tfvars
  examples/compute/virtual_machine/210-vm-bastion-winrm/standalone/variables.tf
  examples/compute/virtual_machine/210-vm-bastion-winrm/virtual_machines.tfvars
  examples/compute/virtual_machine/211-vm-bastion-winrm-agents/registry/variables.tf
  examples/cosmos_db/100-simple-cosmos-db-cassandra/standalone/variables.tf
  examples/cosmos_db/100-simple-cosmos-db-gremlin/standalone/variables.tf
  examples/cosmos_db/100-simple-cosmos-db-mongo/standalone/variables.tf
  examples/cosmos_db/100-simple-cosmos-db-table/standalone/variables.tf
  examples/mssql_mi/standalone/variables.tf
  examples/netapp/101-nfs/standalone/variables.tf
  examples/networking/express_routes/standalone/variables.tf
  examples/networking/private_links/endpoints/centralized/standalone/variables.tf
  landingzones/caf_solution/add-ons/databricks/variables.tf
  modules/compute/virtual_machine/network_interface.tf
  modules/compute/virtual_machine/variables.tf
  modules/networking/network_security_group/diagnostics.tf
  modules/networking/network_security_group/main.tf
  modules/networking/network_security_group/module.tf
  modules/networking/network_security_group/variables.tf
  network_security_groups.tf
  virtual_machines.tf
Labels: enhancement

#345 Name composition logic
  locals.tf
  modules/azuread/applications/module.tf
  modules/azuread/groups/group.tf
Labels: bug

#346 Add Application Security Groups to Nic and NSG
  application_security_groups.tf
  examples/compute/virtual_machine/210-vm-bastion-winrm/nsg_definitions.tfvars
  examples/compute/virtual_machine/210-vm-bastion-winrm/readme.md
  examples/compute/virtual_machine/210-vm-bastion-winrm/standalone/main.tf
  examples/compute/virtual_machine/210-vm-bastion-winrm/standalone/module.tf
  examples/compute/virtual_machine/210-vm-bastion-winrm/standalone/readme.md
  examples/compute/virtual_machine/210-vm-bastion-winrm/virtual_machines.tfvars
  examples/variables.tf
  landingzones/caf_example/module.tf
  landingzones/caf_example/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/compute/virtual_machine/application_security_group.tf
  modules/compute/virtual_machine/network_interface.tf
  modules/compute/virtual_machine/output.tf
  modules/compute/virtual_machine/variables.tf
  modules/networking/application_security_group/main.tf
  modules/networking/application_security_group/module.tf
  modules/networking/application_security_group/output.tf
  modules/networking/application_security_group/variables.tf
  modules/networking/networking_interface_asg_association/asg_associations.tf
  modules/networking/networking_interface_asg_association/main.tf
  modules/networking/networking_interface_asg_association/output.tf
  modules/networking/networking_interface_asg_association/variables.tf
  modules/networking/virtual_network/module.tf
  modules/networking/virtual_network/nsg/module.tf
  modules/networking/virtual_network/nsg/variables.tf
  modules/networking/virtual_network/variables.tf
  networking.tf
  variables.tf
  virtual_machines.tf
Labels: enhancement

#296 Disk Encryption Set with CMK
  .devcontainer/devcontainer.json
  .github/workflows/master-100-tf13.yaml
  .github/workflows/master-100-tf14.yaml
  .github/workflows/master-100-tf15.yaml
  .github/workflows/master-standalone-tf13.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  disk_encryption_sets.tf
  examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars
  examples/compute/virtual_machine/100-single-linux-vm/readme.md
  examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/configuration.tfvars
  examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/standalone/main.tf
  examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/standalone/module.tf
  examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/standalone/variables.tf
  examples/compute/virtual_machine/210-vm-bastion-winrm/standalone/ci.sh
  examples/compute/virtual_machine/212-vm-disk-encryption-set/configurations.tfvars
  keyvault.tf
  keyvault_keys.tf
  landingzones/caf_example/module.tf
  landingzones/caf_example/variables.tf
  landingzones/caf_solution/add-ons/databricks/variables.tf
  load_balancers.tf
  locals.combined_objects.tf
  locals.tf
  modules/compute/virtual_machine/variables.tf
  modules/compute/virtual_machine/vm_disk.tf
  modules/compute/virtual_machine/vm_linux.tf
  modules/compute/virtual_machine/vm_windows.tf
  modules/security/disk_encryption_set/disk_encryption_set.tf
  modules/security/disk_encryption_set/keyvault_policy.tf
  modules/security/disk_encryption_set/main.tf
  modules/security/disk_encryption_set/output.tf
  modules/security/disk_encryption_set/variables.tf
  modules/security/keyvault_access_policies/policies.tf
  modules/security/keyvault_key/key.tf
  modules/security/keyvault_key/main.tf
  modules/security/keyvault_key/variables.tf
  modules/storage_account/output.tf
  virtual_machines.tf
Labels: enhancement

#350 Update a condition on existing NSG with no ASG
  .devcontainer/docker-compose.yml
  .github/workflows/master-100-tf14.yaml
  .github/workflows/master-sql-mi-tf14.yaml
  .github/workflows/master-standalone-tf14.yaml
  modules/networking/virtual_network/nsg/module.tf
Labels: bug

#354 https://github.com/aztfmod/terraform-azurerm-caf/issues/281
  examples/synapse_analytics/100-synapse/configuration.tfvars
  examples/synapse_analytics/101-synapse-sparkpool/configuration.tfvars
  modules/analytics/synapse/workspace.tf
Labels: enhancement

#356 rebased master and added example configuration for mssql db msi auth
  examples/mssql_server/106-sqlserver-db-msi-authentication/configurations.tfvars
Labels: documentation

#357 Add cert name support for AGW and Fix remote LZ bugs in SQL MI for location and base tags
  .github/workflows/master-sql-mi-tf13.yaml
  .github/workflows/master-sql-mi-tf14.yaml
  .github/workflows/master-sql-mi-tf15.yaml
  examples/app_gateway/210-agw-with-keyvault/application.tfvars
  landingzones/caf_example/module.tf
  landingzones/caf_example/variables.tf
  modules/networking/application_gateway/application_gateway.tf
  msssql_managed_databases.tf
Labels: bug, enhancement
