Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2021-08, with the labels that each got.

#612 Correction on subid output for importing subscription
  modules/subscriptions/output.tf
Labels: bug

#608 Fix application gateway issue with empty fqdn
  modules/networking/application_gateway/application_gateway.tf
Labels: bug

#609 fix: temp move consumption budget to separate file
  .github/workflows/standalone-scenarios-additional.json
  .github/workflows/standalone-scenarios.json
  examples/consumption_budget/README.md
Labels: CI

#611 Update to support more resource reference in RT nexthop
  modules/networking/virtual_hub_route_tables/route_local.tf
  modules/networking/virtual_hub_route_tables/variables.tf
  networking_virtual_hub_route_table.tf
Labels: enhancement

#618 Fix subnet optional in secure hub firewall
  networking_firewall.tf
Labels: bug

#620 uncomment to add support for skuEdition for sqlmi
  modules/databases/mssql_managed_instance/main.tf
Labels: enhancement

#621 Add Ability to Enter admin_password
  modules/compute/virtual_machine/vm_linux.tf
Labels: enhancement

#625 VM module to only ignore OS disk name change
  modules/compute/virtual_machine/vm_linux.tf
  modules/compute/virtual_machine/vm_windows.tf
Labels: enhancement

#626 Storage - Add files to storage shares
  examples/storage_accounts/104-file-share-with-backup/configuration.tfvars
  examples/storage_accounts/104-file-share-with-backup/fileA
  examples/storage_accounts/104-file-share-with-backup/fileB
  examples/storage_accounts/104-file-share-with-backup/fileC
  modules/storage_account/file_share/share_file.tf
  modules/storage_account/file_share_file/file.tf
  modules/storage_account/file_share_file/output.tf
  modules/storage_account/file_share_file/variables.tf
Labels: enhancement

#627 Ssh host rover support
  .devcontainer/devcontainer.json
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  main.tf
  modules/azuread/applications/scripts/grant_consent.sh
  modules/azuread/service_principal/scripts/grant_consent.sh
  modules/security/keyvault_access_policies/policies.tf
  modules/subscriptions/output.tf
  rover_on_ssh_host.yml
Labels: bug

#629 Update azurerm to 2.70.0 - fix ci - fmt
  .github/workflows/standalone-scenarios-additional.json
  .github/workflows/standalone-scenarios.json
  aks_clusters.tf
  examples/ci.sh
  examples/storage_accounts/104-file-share-with-backup/configuration.tfvars
  main.tf
  networking.tf
  networking_firewall.tf
  networking_virtual_hub_route_table.tf
  roles.tf
Labels: enhancement

#645 Fix start date used in expiration date calculation
  modules/azuread/credentials/password.tf
  modules/azuread/credentials/password_rotation.tf
Labels: bug

#637 Update Example on remote lz for user msi in vm
  examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars
Labels: documentation

#642 Update azuread_application.tf
  modules/azuread/applications_v1/azuread_application.tf
Labels: enhancement

#650 fix sqlmi example to update on password handling
  examples/mssql_mi/200-mi-two-regions/configuration.tfvars
  examples/mssql_mi/200-mi/configuration.tfvars
Labels: bug

#638 Custom Data - Allow Txt for `custom_data` on linux vm creation
  examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars
  modules/compute/virtual_machine/vm_linux.tf
Labels: enhancement
