Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2021-02, with the labels that each got.

#243 Update readme for terraform registry
  modules/compute/virtual_machine/README.md
  modules/compute/virtual_machine/private_module_README.md
Labels: 5.1.0, documentation

#245 Hn aks
  application_gateways.tf
  front_doors.tf
  keyvault_certificate_requests.tf
  main.tf
  modules/compute/aks/aks.tf
  modules/networking/application_gateway/application_gateway.tf
  modules/networking/application_gateway/variable.tf
Labels: 5.1.0, enhancement

#246 Adding dependency on cert requests for App Gateways
  application_gateways.tf
  modules/compute/aks/README.md
  modules/compute/aks/aks.tf
Labels: 5.1.0, bug

#264 add minimum_tls_version to sql server
  modules/databases/mssql_server/server.tf
Labels: bug

#260 fix tag merging sequence
  modules/analytics/databricks_workspace/main.tf
  modules/analytics/machine_learning/main.tf
  modules/analytics/synapse/main.tf
  modules/app_insights/main.tf
  modules/automation/main.tf
  modules/compute/aks/main.tf
  modules/compute/availability_set/main.tf
  modules/compute/container_registry/main.tf
  modules/compute/proximity_placement_group/main.tf
  modules/compute/virtual_machine/main.tf
  modules/databases/cosmos_db/main.tf
  modules/databases/mariadb_server/main.tf
  modules/databases/mssql_database/main.tf
  modules/databases/mssql_elastic_pool/main.tf
  modules/databases/mssql_server/main.tf
  modules/databases/mysql_server/main.tf
  modules/databases/postgresql_server/main.tf
  modules/event_hub_namespaces/main.tf
  modules/log_analytics/main.tf
  modules/netapp/main.tf
  modules/networking/application_gateway/main.tf
  modules/networking/express_route_circuit/main.tf
  modules/networking/express_route_circuit_authorization/main.tf
  modules/networking/firewall/main.tf
  modules/networking/front_door/main.tf
  modules/networking/front_door_waf_policy/main.tf
  modules/networking/local_network_gateways/main.tf
  modules/networking/network_watcher/main.tf
  modules/networking/private-dns/main.tf
  modules/networking/private_endpoint/main.tf
  modules/networking/private_links/endpoints/main.tf
  modules/networking/private_links/endpoints/private_endpoint/main.tf
  modules/networking/public_ip_addresses/main.tf
  modules/networking/route_tables/main.tf
  modules/networking/virtual_network/main.tf
  modules/networking/virtual_network_gateway_connections/main.tf
  modules/networking/virtual_network_gateways/main.tf
  modules/networking/virtual_wan/main.tf
  modules/recovery_vault/main.tf
  modules/redis_cache/main.tf
  modules/security/keyvault_key/key.tf
  modules/security/managed_identity/main.tf
  modules/webapps/appservice/main.tf
  modules/webapps/asp/main.tf
Labels: bug

#257 support app service backup
  .github/workflows/master-100-tf14.yaml
  .github/workflows/master-100-tf15.yaml
  .github/workflows/master-100.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  .github/workflows/master-standalone.yaml
  app_services.tf
  examples/outputs.tf
  examples/webapps/appservice/105-appservice-backup/configuration.tfvars
  examples/webapps/appservice/105-appservice-backup/standalone/ci.sh
  examples/webapps/appservice/105-appservice-backup/standalone/main.tf
  examples/webapps/appservice/105-appservice-backup/standalone/module.tf
  examples/webapps/appservice/105-appservice-backup/standalone/readme.md
  examples/webapps/appservice/105-appservice-backup/standalone/variables.tf
  modules/storage_account/output.tf
  modules/webapps/appservice/main.tf
  modules/webapps/appservice/module.tf
  modules/webapps/appservice/storage_account.tf
  modules/webapps/appservice/variables.tf
Labels: enhancement

#265 Fix BGP Settings in Virtual Network Gateway and Local Network Gateway modules
  examples/networking/virtual_network_gateway/101-vpn-site-to-site/configuration.tfvars
  modules/networking/local_network_gateways/module.tf
  modules/networking/virtual_network_gateways/module.tf
Labels: bug

#268 Adding release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: CI, enhancement

#259 #258 Added support for mssql_database.storage_account_type
  modules/databases/mssql_database/database.tf
Labels: bug

#269 Added support for mssql_database.storage_account_type #258
  modules/databases/mssql_database/database.tf
Labels: bug

#266 Bugfix for Azure Bastion
  aks_clusters.tf
  bastion_service.tf
Labels: bug

#267 Hn aks
  application_gateways.tf
  keyvault_certificate_requests.tf
  modules/compute/aks/aks.tf
  modules/networking/application_gateway/application_gateway.tf
  modules/networking/application_gateway/locals.tf
  modules/networking/application_gateway/variable.tf
  modules/networking/firewall/module.tf
  modules/networking/firewall/variables.tf
  modules/security/keyvault_certificate_request/module.tf
  modules/security/keyvault_certificate_request/variables.tf
  networking_firewall.tf
Labels: enhancement

#276 private-dns. Add registration_enabled and tags
  modules/networking/private-dns/virtual_network_link.tf
Labels: enhancement

#277 Adding support path routing on AGW
  modules/networking/application_gateway/application_gateway.tf
  modules/networking/application_gateway/locals.tf
Labels: enhancement

#282 bump azurecaf version
  examples/main.tf
Labels: enhancement

#291 Refactor sql server kv
  .github/workflows/master-100-tf14.yaml
  .github/workflows/master-100-tf15.yaml
  .github/workflows/master-100.yaml
  .github/workflows/master-standalone-tf14.yaml
  .github/workflows/master-standalone-tf15.yaml
  .github/workflows/master-standalone.yaml
  examples/mssql_server/101-sqlserver-simple/configuration.tfvars
  examples/mssql_server/102-sqlserver-extend/configuration.tfvars
  examples/mssql_server/103-sqlserver-two-regions/configuration.tfvars
  examples/mssql_server/104-sqlserver-elastic_pools/configuration.tfvars
  examples/mssql_server/104-sqlserver-elastic_pools/standalone/ci.sh
  examples/mssql_server/104-sqlserver-elastic_pools/standalone/main.tf
  examples/mssql_server/104-sqlserver-elastic_pools/standalone/module.tf
  examples/mssql_server/104-sqlserver-elastic_pools/standalone/readme.md
  examples/mssql_server/104-sqlserver-elastic_pools/standalone/variables.tf
  examples/mssql_server/105-sqlserver-failover_groups/configuration.tfvars
  examples/mssql_server/105-sqlserver-failover_groups/standalone/ci.sh
  examples/mssql_server/105-sqlserver-failover_groups/standalone/main.tf
  examples/mssql_server/105-sqlserver-failover_groups/standalone/module.tf
  examples/mssql_server/105-sqlserver-failover_groups/standalone/readme.md
  examples/mssql_server/105-sqlserver-failover_groups/standalone/variables.tf
  modules/databases/mssql_server/output.tf
  modules/databases/mssql_server/server.tf
  modules/databases/mssql_server/variables.tf
  modules/webapps/appservice/storage_account.tf
  mssql_servers.tf
Labels: bug
