Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2021-07, with the labels that each got.

#555 Update remote RG structure for selected modules
  application_gateways.tf
  keyvault.tf
  load_balancers.tf
  modules/networking/application_gateway/locals.networking.tf
  modules/security/keyvault/keyvault.tf
  modules/security/keyvault/private_endpoints.tf
  networking.tf
  virtual_machines.tf
Labels: enhancement

#558 Adding timer post MSI creation
  examples/storage_accounts/104-file-share-with-backup/configuration.tfvars
  modules/azuread/service_principal/module.tf
  modules/security/managed_identity/managed_identity.tf
  storage_account_blobs.tf
Labels: bug

#561 Feature/consumption-budgets
  .github/workflows/standalone-scenarios.json
  consumption_budgets.tf
  examples/consumption_budget/100-consumption-budget-rg/configuration.tfvars
  examples/consumption_budget/101-consumption-budget-subscription/configuration.tfvars
  examples/consumption_budget/102-consumption-budget-rg-alerts/configuration.tfvars
  examples/consumption_budget/103-consumption-budget-subscription-alerts/configuration.tfvars
  examples/consumption_budget/README.md
  examples/consumption_budget/main.tf
  examples/module.tf
  examples/monitoring/101-monitor-action-groups/configuration.tfvars
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/consumption_budget/resource_group/main.tf
  modules/consumption_budget/resource_group/output.tf
  modules/consumption_budget/resource_group/resource_group_budget.tf
  modules/consumption_budget/resource_group/variables.tf
  modules/consumption_budget/subscription/main.tf
  modules/consumption_budget/subscription/output.tf
  modules/consumption_budget/subscription/subscription_budget.tf
  modules/consumption_budget/subscription/variables.tf
  modules/monitoring/monitor_action_group/main.tf
  modules/monitoring/monitor_action_group/monitor_action_group.tf
  modules/monitoring/monitor_action_group/output.tf
  modules/monitoring/monitor_action_group/variables.tf
  modules/monitoring/service_health_alerts/service_health_alert.tf
  monitor_action_groups.tf
Labels: enhancement, new submodule

#565 Add firewall policy parent child
  modules/networking/firewall_policies/firewall_policy.tf
  modules/networking/firewall_policies/locals.tf
  modules/networking/firewall_policies/output.tf
  modules/networking/firewall_policies/variables.tf
  networking_firewall.tf
  networking_firewall_policy.tf
Labels: enhancement

#566 Add route_table next_hop
  modules/networking/virtual_hub_route_tables/route_local.tf
  networking_virtual_hub_connection.tf
  networking_virtual_hub_route_table.tf
Labels: bug

#577 Fix vhub connection outputs name
  networking_virtual_hub_connection.tf
Labels: bug

#572 added support for specifying application gateway WAF config
  modules/networking/application_gateway/application_gateway.tf
Labels: enhancement

#563 Add support for random password in SQL MI
  examples/mssql_mi/200-mi/configuration.tfvars
  examples/mssql_server/101-sqlserver-simple/configuration.tfvars
  examples/mssql_server/106-sqlserver-db-msi-authentication/configurations.tfvars
  examples/mssql_server/107-sqlserver-db-retention-policy/configurations.tfvars
  examples/mssql_server/108-sqlserver-db-diagnostics/configurations.tfvars
  examples/mssql_server/109-sqlserver-network-firewall-rule/configurations.tfvars
  modules/databases/mssql_managed_instance/main.tf
  modules/databases/mssql_managed_instance/managed_instance.tf
  modules/databases/mssql_managed_instance/variables.tf
  modules/databases/mssql_server/output.tf
  modules/databases/mssql_server/server.tf
  modules/databases/mssql_server/variables.tf
  mssql_servers.tf
  msssql_managed_instances.tf
Labels: enhancement

#573 added support for specifying host name on backend http settings
  modules/networking/application_gateway/application_gateway.tf
Labels: enhancement

#578 Modernize old aad_apps policy
  README.md
  modules/security/keyvault_access_policies/policies.tf
Labels: bug

#574 added support for configuring application gateway health probes and assigning to backend settings
  examples/app_gateway/100-simple-app-gateway/application.tfvars
  modules/networking/application_gateway/application_gateway.tf
  modules/networking/application_gateway/locals.tf
Labels: enhancement

#571 #487 Corrected name from private_key to public_key
  modules/compute/virtual_machine/output.tf
  modules/compute/virtual_machine_scale_set/output.tf
  networking.tf
Labels: bug

#581 Add NAT Gateway sub module
  .github/workflows/standalone-scenarios.json
  examples/networking/nat_gateways/100-nat-gateways-with-public-ip/networking.tfvars
  locals.combined_objects.tf
  locals.tf
  modules/networking/nat_gateways/main.tf
  modules/networking/nat_gateways/module.tf
  modules/networking/nat_gateways/output.tf
  modules/networking/nat_gateways/public_ip_association/module.tf
  modules/networking/nat_gateways/public_ip_association/variables.tf
  modules/networking/nat_gateways/subnet_association/module.tf
  modules/networking/nat_gateways/subnet_association/variables.tf
  modules/networking/nat_gateways/variables.tf
  networking_nat_gateways.tf
Labels: new submodule

#587 Fix event hub private link issue 583
  event_hubs.tf
Labels: bug

#588 fixed resolving of backend address pool name for application gateway path rule
  modules/networking/application_gateway/application_gateway.tf
Labels: bug

#594 Fix the bugs in AKS specific examples
  examples/compute/kubernetes_services/103-multi-clusters/aks.tfvars
  examples/compute/kubernetes_services/103-multi-clusters/networking.tfvars
  examples/compute/kubernetes_services/104-private-cluster/acr.tfvars
  examples/compute/kubernetes_services/104-private-cluster/aks.tfvars
  examples/compute/kubernetes_services/104-private-cluster/configuration.tfvars
  examples/compute/kubernetes_services/104-private-cluster/diagnostics.tfvars
  examples/compute/kubernetes_services/104-private-cluster/networking.tfvars
  examples/compute/kubernetes_services/104-private-cluster/vm.tfvars
Labels: bug

#601 Fix routes to handle null error
  networking.tf
Labels: bug

#585 Add support for a creating an AKS cluster using user managed identity
  aks_clusters.tf
  examples/compute/kubernetes_services/105-cluster-usermsi/aks.tfvars
  examples/compute/kubernetes_services/105-cluster-usermsi/diagnostics.tfvars
  examples/compute/kubernetes_services/105-cluster-usermsi/networking.tfvars
  modules/compute/aks/aks.tf
  modules/compute/aks/variables.tf
Labels: enhancement

#605 ci/ignore all README file updates
  .github/workflows/master-standalone-tf100.yaml
Labels: enhancement

#592 Support for application gateway rewrite rule sets
  examples/app_gateway/101-private-public/application.tfvars
  examples/app_gateway/101-private-public/application_gateways.tfvars
  modules/networking/application_gateway/application_gateway.tf
  modules/networking/application_gateway/locals.tf
Labels: enhancement

#591 Fix pre-existing network watcher #527
  examples/networking/virtual_network/202-nsg-flow-logs-v2/configuration.tfvars
  examples/networking/virtual_network/202-nsg-flow-logs-v2/diagnostics_definitions.tfvars
  examples/networking/virtual_network/202-nsg-flow-logs-v2/diagnostics_destinations.tfvars
  examples/networking/virtual_network/202-nsg-flow-logs-v2/nsg_definitions.tfvars
  modules/networking/network_security_group/nsg_flow_logs.tf
  modules/networking/network_security_group/variables.tf
  modules/networking/network_watcher/output.tf
  modules/networking/virtual_network/module.tf
  modules/networking/virtual_network/nsg/flow_logs/flow_logs.tf
  modules/networking/virtual_network/nsg/flow_logs/variables.tf
  modules/networking/virtual_network/nsg/nsg_flow_logs.tf
  network_security_groups.tf
  networking.tf
Labels: bug

#590 Adding p2s support to virtual gateway
  examples/networking/virtual_network_gateway/104-vpn-point-to-site-gateway/configuration.tfvars
  modules/networking/virtual_network_gateways/module.tf
Labels: enhancement

#604 Integration sub module/cognitive service
  .devcontainer/docker-compose.yml
  .github/workflows/standalone-scenarios.json
  cognitive_service.tf
  examples/cognitive_services/100-cognitive-services-account/configuration.tfvars
  examples/cognitive_services/main.tf
  examples/module.tf
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/cognitive_services/cognitive_services_account/cognitive_service_account.tf
  modules/cognitive_services/cognitive_services_account/main.tf
  modules/cognitive_services/cognitive_services_account/output.tf
  modules/cognitive_services/cognitive_services_account/variables.tf
  networking_firewall_policy.tf
  networking_nat_gateways.tf
  networking_virtual_hub_connection.tf
  variables.tf
Labels: new submodule

#603 Feature/managed identity remote
  examples/managed_service_identity/100-msi-levels/configuration.tfvars
  examples/managed_service_identity/README.md
  managed_identities.tf
  modules/security/managed_identity/managed_identity.tf
  modules/security/managed_identity/variables.tf
Labels: enhancement

#600 Add remote role mapping scope support
  .github/workflows/standalone-scenarios.json
  examples/role_mapping/100-simple-role-mapping/configuration.tfvars
  roles.tf
Labels: enhancement

#584 BugFix: Fix the private dns zone id key and variables in the aks module
  aks_clusters.tf
  modules/compute/aks/aks.tf
Labels: enhancement

#606 refactor to use coalsece for roles
  roles.tf
Labels: bug
