Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2022-02, with the labels that each got.

#916 Update Terraform native workflows
  .github/workflows/master-standalone-tf100.yaml
  .github/workflows/master-standalone-tf15.yaml
  .github/workflows/standalone-regressor-tf100.yaml
  .github/workflows/standalone-regressor-tf15.yaml
  .github/workflows/standalone-tf100.yaml
  .github/workflows/standalone-tf15.yaml
  examples/compute/dedicated_hosts/102-dedicated-host-vms/vm.tfvars
  examples/databricks/102-premium-aml/configuration.tfvars
  examples/machine_learning/100-aml/configuration.tfvars
  examples/machine_learning/101-aml-vnet/configuration.tfvars
  examples/machine_learning/102-aml-compute_instance/configuration.tfvars
  examples/machine_learning/103-aml-compute_instance_assing-to-user/configuration.tfvars
  modules/analytics/machine_learning/workspace.tf
Labels: enhancement

#908 Adding Activity Log Alert & Metric Alert
  .github/workflows/standalone-scenarios.json
  examples/apim/109-api_management_custom_domain/configuration.tfvars
  examples/module.tf
  examples/monitoring/102-monitor_activity_log_alert/configuration.tfvars
  examples/monitoring/103-monitor_metric_alert/configuration.tfvars
  examples/variables.tf
  local.remote_objects.tf
  locals.tf
  modules/monitoring/monitor_activity_log_alert/README.md
  modules/monitoring/monitor_activity_log_alert/main.tf
  modules/monitoring/monitor_activity_log_alert/module.tf
  modules/monitoring/monitor_activity_log_alert/output.tf
  modules/monitoring/monitor_activity_log_alert/variables.tf
  modules/monitoring/monitor_metric_alert/README.md
  modules/monitoring/monitor_metric_alert/main.tf
  modules/monitoring/monitor_metric_alert/module.tf
  modules/monitoring/monitor_metric_alert/output.tf
  modules/monitoring/monitor_metric_alert/variables.tf
  monitoring.tf
Labels: new submodule

#723 Adding Azure Data Explorer
  .github/workflows/standalone-scenarios.json
  data_explorer.tf
  examples/data_explorer/101-kusto_clusters_basic/configuration.tfvars
  examples/data_explorer/102-kusto_clusters_vnet/configuration.tfvars
  examples/data_explorer/103-kusto_clusters_identity/configuration.tfvars
  examples/data_explorer/104-kusto_cluster_database/configuration.tfvars
  examples/data_explorer/105-kusto_attached_database_configuration/configuration.tfvars
  examples/data_explorer/106-database_principal_assignment/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/databases/data_explorer/kusto_attached_database_configurations/main.tf
  modules/databases/data_explorer/kusto_attached_database_configurations/module.tf
  modules/databases/data_explorer/kusto_attached_database_configurations/output.tf
  modules/databases/data_explorer/kusto_attached_database_configurations/variables.tf
  modules/databases/data_explorer/kusto_cluster_customer_managed_keys/main.tf
  modules/databases/data_explorer/kusto_cluster_customer_managed_keys/module.tf
  modules/databases/data_explorer/kusto_cluster_customer_managed_keys/output.tf
  modules/databases/data_explorer/kusto_cluster_customer_managed_keys/variables.tf
  modules/databases/data_explorer/kusto_cluster_principal_assignments/main.tf
  modules/databases/data_explorer/kusto_cluster_principal_assignments/module.tf
  modules/databases/data_explorer/kusto_cluster_principal_assignments/output.tf
  modules/databases/data_explorer/kusto_cluster_principal_assignments/variables.tf
  modules/databases/data_explorer/kusto_clusters/main.tf
  modules/databases/data_explorer/kusto_clusters/managed_identities.tf
  modules/databases/data_explorer/kusto_clusters/module.tf
  modules/databases/data_explorer/kusto_clusters/output.tf
  modules/databases/data_explorer/kusto_clusters/variables.tf
  modules/databases/data_explorer/kusto_database_principal_assignments/main.tf
  modules/databases/data_explorer/kusto_database_principal_assignments/module.tf
  modules/databases/data_explorer/kusto_database_principal_assignments/output.tf
  modules/databases/data_explorer/kusto_database_principal_assignments/variables.tf
  modules/databases/data_explorer/kusto_databases/main.tf
  modules/databases/data_explorer/kusto_databases/module.tf
  modules/databases/data_explorer/kusto_databases/output.tf
  modules/databases/data_explorer/kusto_databases/variables.tf
  modules/databases/data_explorer/kusto_eventgrid_data_connections/main.tf
  modules/databases/data_explorer/kusto_eventgrid_data_connections/module.tf
  modules/databases/data_explorer/kusto_eventgrid_data_connections/output.tf
  modules/databases/data_explorer/kusto_eventgrid_data_connections/variables.tf
  modules/databases/data_explorer/kusto_eventhub_data_connections/main.tf
  modules/databases/data_explorer/kusto_eventhub_data_connections/module.tf
  modules/databases/data_explorer/kusto_eventhub_data_connections/output.tf
  modules/databases/data_explorer/kusto_eventhub_data_connections/variables.tf
  modules/databases/data_explorer/kusto_iothub_data_connections/main.tf
  modules/databases/data_explorer/kusto_iothub_data_connections/module.tf
  modules/databases/data_explorer/kusto_iothub_data_connections/output.tf
  modules/databases/data_explorer/kusto_iothub_data_connections/variables.tf
Labels: new submodule

#920 Add support for APIM Gateway
  .github/workflows/standalone-scenarios-longrunners.json
  api_management.tf
  examples/README.md
  examples/apim/112-api_management_gateway/configuration.tfvars
  examples/apim/113-api_management_gateway_api/configuration.tfvars
  examples/apim/114-api-management-group/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/apim/api_management_gateway/main.tf
  modules/apim/api_management_gateway/module.tf
  modules/apim/api_management_gateway/output.tf
  modules/apim/api_management_gateway/variables.tf
  modules/apim/api_management_gateway_api/main.tf
  modules/apim/api_management_gateway_api/module.tf
  modules/apim/api_management_gateway_api/output.tf
  modules/apim/api_management_gateway_api/variables.tf
  modules/apim/api_management_group/main.tf
  modules/apim/api_management_group/module.tf
  modules/apim/api_management_group/output.tf
  modules/apim/api_management_group/variables.tf
Labels: new submodule

#947 Update standalone.md to fix typo
  examples/standalone.md
Labels: documentation

#932 Add jsonencode to convert settings value to string
  modules/compute/virtual_machine_scale_set/vmss_windows.tf
Labels: bug

#890 Allow cross zone creation of keyvault cert requests from dns registra…
  examples/keyvault/103-keyvault-cert-request/README.md
  examples/keyvault/103-keyvault-cert-request/configuration.tfvars
  keyvault_certificate_requests.tf
  locals.combined_objects.tf
  modules/security/keyvault_certificate_request/module.tf
  modules/security/keyvault_certificate_request/variables.tf
Labels: do not merge

#936 APIM Name Provider Resource Type Fix
  modules/apim/api_management/module.tf
  modules/apim/api_management_api/module.tf
  modules/apim/api_management_gateway/module.tf
  modules/apim/api_management_group/module.tf
  modules/apim/api_management_logger/module.tf
Labels: bug

#949 MSSQL Redeploy on adding new SQL Server
  modules/databases/mssql_database/database.tf
Labels: bug

#917 Conditional improvements to autoscale module
  modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
Labels: enhancement
