Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2022-05, with the labels that each got.

#1139 Bugfix/add missing output front door
  modules/networking/front_door/output.tf
Labels: bug, front door

#1142 [front door rules engine] Bugfix response header dynamic block
  examples/networking/front_door/102-front_door_advanced/front_door_rules_engine.tfvars
  modules/networking/frontdoor_rules_engine/module.tf
Labels: bug

#1135 Bugfix add missing custom_block_response_body fallback
  modules/networking/front_door_waf_policy/waf_policy.tf
Labels: bug, front door

#1140 fixes remote lz logic w/ private endpoint resource groups
  data_factory.tf
  modules/data_factory/data_factory/private_endpoints.tf
Labels: bug

#1110 Backup Vault for storage account / managed disk
  .github/workflows/standalone-scenarios.json
  backup_vaults.tf
  examples/data_protection/100-backup-vault-blob-storage/configuration.tfvars
  examples/data_protection/101-backup-vault-disk/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/backup_vault/backup_vault.tf
  modules/backup_vault/backup_vault_instance_blob_storage/backup_vault_instance_blob_storage.tf
  modules/backup_vault/backup_vault_instance_blob_storage/variables.tf
  modules/backup_vault/backup_vault_instance_disk/backup_vault_instance_disk.tf
  modules/backup_vault/backup_vault_instance_disk/variables.tf
  modules/backup_vault/backup_vault_policy_blob_storage/backup_vault_policy.tf
  modules/backup_vault/backup_vault_policy_blob_storage/outputs.tf
  modules/backup_vault/backup_vault_policy_blob_storage/variables.tf
  modules/backup_vault/backup_vault_policy_disk/backup_vault_policy.tf
  modules/backup_vault/backup_vault_policy_disk/outputs.tf
  modules/backup_vault/backup_vault_policy_disk/variables.tf
  modules/backup_vault/main.tf
  modules/backup_vault/outputs.tf
  modules/backup_vault/variables.tf
  modules/compute/virtual_machine/output.tf
  modules/storage_account/output.tf
  roles.tf
  storage_accounts.tf
  variables.tf
Labels: enhancement

#1152 Fixed function_app values
  modules/webapps/function_app/module.tf
Labels: bug, function

#1149 API management subscription
  .github/workflows/standalone-scenarios-longrunners.json
  api_management.tf
  examples/apim/116-api_management_subscription/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  locals.tf
  modules/apim/api_management_subscription/main.tf
  modules/apim/api_management_subscription/module.tf
  modules/apim/api_management_subscription/output.tf
  modules/apim/api_management_subscription/variables.tf
Labels: enhancement, apim

#1123 Adds support for Synapse Workspace Private Endpoints
  modules/analytics/synapse/private_endpoints.tf
  modules/analytics/synapse/variables.tf
  synapses.tf
Labels: enhancement

#1164 Make azuread_groups_membership module landingzone aware
  azuread_groups.tf
  examples/azuread/104-azuread-group-membership/configuration.tfvars
Labels: enhancement, azuread

#1078 Fix VM scale set LB assignment and add new LB module variable to VM scale set module
  examples/compute/virtual_machine_scale_set/106-linux-win-vmss-lb/configurations.tfvars
  modules/compute/virtual_machine_scale_set/main.tf
  modules/compute/virtual_machine_scale_set/variables.tf
  modules/compute/virtual_machine_scale_set/vmss_linux.tf
  modules/compute/virtual_machine_scale_set/vmss_windows.tf
  virtual_machines_scale_sets.tf
Labels: enhancement, networking, load balancer, linux, compute, vmss

#1169 Add private endpoints for redis
  .github/workflows/standalone-scenarios.json
  examples/redis_cache/103-redis-private-endpoints/configuration.tfvars
  modules/redis_cache/private_endpoints.tf
  modules/redis_cache/variables.tf
  redis_caches.tf
Labels: enhancement, redis, private endpoints

#1171 Added private_ip_ranges for azurerm_firewall_policy
  modules/networking/firewall_policies/firewall_policy.tf
Labels: enhancement

#1172 Add vnet DNS support
  .github/workflows/standalone-scenarios.json
  examples/networking/lb/102-vm_lb_dns_servers/configurations.tfvars
  examples/networking/load_balancers/100-simple-load-balancer-basic-sku/configuration.tfvars
  examples/networking/load_balancers/101-load-balancer-with-rules/configuration.tfvars
  examples/networking/load_balancers/102-internal-load-balancer/configuration.tfvars
  examples/networking/load_balancers/104-load-balancer-diagnostics/configuration.tfvars
  examples/networking/load_balancers/104-load-balancer-diagnostics/diagnostics.tfvars
  examples/networking/virtual_network/100-simple-vnet-subnets-nsgs/configuration.tfvars
  load_balancers.tf
  modules/networking/load_balancers/load_balancers.tf
  modules/networking/load_balancers/variables.tf
  modules/networking/virtual_network/module.tf
  networking.tf
Labels: enhancement, virtual network

#1174 Support remote keyvault for SQL MI admin password
  examples/mssql_mi/200-mi-two-regions/configuration.tfvars
  examples/mssql_mi/200-mi/configuration.tfvars
  modules/databases/mssql_managed_instance/administrator/scripts/set_mi_ad_admin.sh
  modules/databases/mssql_managed_instance/arm_sql_mi.json
  modules/databases/mssql_managed_instance/main.tf
  modules/databases/mssql_managed_instance/managed_instance.tf
  modules/databases/mssql_managed_instance/variables.tf
  msssql_managed_instances.tf
Labels: bug

#1175 use `ignore_missing_property` to suppress diff
  modules/databases/mssql_managed_instance/managed_instance.tf
Labels: bug, sqlmi

#1176 Updating Application Gateway TLS certificates ingestion
  modules/networking/application_gateway_application/http_listener.tf
  modules/networking/application_gateway_application/root_cert.tf
  modules/networking/application_gateway_platform/application_gateway.tf
Labels: enhancement, app_gateway

#1177 Update SQL MI output
  modules/databases/mssql_managed_instance/arm_sql_mi.json
  modules/databases/mssql_managed_instance/managed_instance.tf
  modules/databases/mssql_managed_instance/output.tf
Labels: bug

#1179 Patch fixing SQL MI outputs
  modules/databases/mssql_managed_instance/managed_instance.tf
  modules/databases/mssql_managed_instance/output.tf
  modules/databases/mssql_managed_instance/variables.tf
  msssql_managed_instances.tf
Labels: bug

#1184 Update resource id SQL MI
  modules/databases/mssql_managed_instance/managed_instance.tf
Labels: bug, sqlmi

#1185 Replace objectId with id for az cli 2.37
  .devcontainer/docker-compose.yml
  .github/workflows/standalone-regressor-tf100.yaml
  .github/workflows/standalone-regressor-tf15.yaml
  .github/workflows/standalone-tf100.yaml
  .github/workflows/standalone-tf15.yaml
  modules/azuread/applications/scripts/grant_consent.sh
  modules/azuread/service_principal/scripts/grant_consent.sh
  modules/compute/aks/scripts/grant_consent.sh
Labels: bug

#1115 Add support for Ase v3
  .github/workflows/standalone-scenarios-longrunners.json
  app_service_environments.tf
  app_service_plans.tf
  examples/module.tf
  examples/variables.tf
  examples/webapps/appservice-environment/102-simple_asev3/configuration.tfvars
  local.remote_objects.tf
  locals.combined_objects.tf
  locals.tf
  modules/webapps/asev3/diagnostic.tf
  modules/webapps/asev3/main.tf
  modules/webapps/asev3/module.tf
  modules/webapps/asev3/output.tf
  modules/webapps/asev3/private_dns_records.tf
  modules/webapps/asev3/variables.tf
  roles.tf
Labels: enhancement, app_service

#1153 Added output for eventhubs auth_rules
  event_hubs.tf
  modules/event_hubs/namespaces/auth_rules/output.tf
Labels: enhancement

#1187 Add requestedBackupStorageRedundancy
  modules/databases/mssql_managed_instance/main.tf
Labels: enhancement, sqlmi

#1191 #1190 fix subnet_id evaluation for aks
  aks_clusters.tf
  modules/compute/aks/aks.tf
  modules/compute/aks/variables.tf
Labels: bug, aks

#1107 Add Private Endpoint support for Purview Managed Resources (needs azu…
  examples/purview/101-purview_account_private_link/configuration.tfvars
  modules/purview/purview_accounts/private_endpoints.tf
Labels: enhancement, data services, purview
