Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2022-03, with the labels that each got.

#905 Add native support for tags to subscriptions
  examples/subscriptions/100-create-subscription/configuration.tfvars
  modules/subscriptions/scripts/tags.sh
  modules/subscriptions/subscriptions.tf
  modules/subscriptions/tags.tf
Labels: enhancement

#971 Add support for storage_mode_type in recovery vaults
  modules/recovery_vault/recovery_vault.tf
Labels: enhancement

#969 Adding VMSS/VM Generic Extension and Insights
  .github/workflows/standalone-scenarios.json
  examples/compute/virtual_machine/213-vm_generic_extensions/configurations.tfvars
  examples/compute/virtual_machine/214-vm-generic_extensions_complex/configurations.tfvars
  examples/compute/virtual_machine_scale_set/106-vmss_monitoring/configuration.tfvars
  modules/compute/virtual_machine_extensions/generic_extensions.tf
  modules/compute/virtual_machine_scale_set/vmss_windows.tf
  modules/compute/virtual_machine_scale_set_extensions/dependency_agent.tf
  modules/compute/virtual_machine_scale_set_extensions/microsoft_monitor_agent.tf
  modules/compute/virtual_machine_scale_set_extensions/variables.tf
  modules/log_analytics/output.tf
  virtual_machines_extensions.tf
  virtual_machines_scale_sets_extensions.tf
Labels: new submodule

#972 Application gateway improvements
  modules/networking/application_gateway/application_gateway.tf
Labels: enhancement

#967 Updated Secured vHUB Deployment Example and Route Table for Secured Internet Egress via Secured vHUB
  .github/workflows/standalone-scenarios.json
  examples/networking/virtual_wan/102-vwan-hub-firewall-new/virtual_wan.tfvars
  examples/networking/virtual_wan/102-vwan-hub-firewall-secured-vhub/virtual_wan.tfvars
  examples/networking/virtual_wan/105-vwan-hub-route-table/virtual_wan.tfvars
  modules/networking/firewall/module.tf
Labels: documentation, enhancement

#966 Purview Account
  .github/workflows/standalone-scenarios.json
  examples/module.tf
  examples/purview/100-purview_account/configuration.tfvars
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/purview/purview_account/README.md
  modules/purview/purview_account/diagnostics.tf
  modules/purview/purview_account/main.tf
  modules/purview/purview_account/module.tf
  modules/purview/purview_account/output.tf
  modules/purview/purview_account/variables.tf
  purview.tf
  variables.tf
Labels: new submodule

#1000 Update for 5.5.4
  examples/networking/virtual_wan/105-vwan-hub-route-table/virtual_wan.tfvars
  modules/apim/api_management/output.tf
  modules/networking/firewall/module.tf
  modules/security/dynamic_keyvault_secrets/keyvault.tf
Labels: enhancement

#1014 Fix: Missing parameter sql_username_key causing error
  modules/compute/virtual_machine/mssql_vm.tf
Labels: bug

#1009 Add single_placement_group and overprovision for VMSS
  modules/compute/virtual_machine_scale_set/vmss_linux.tf
Labels: enhancement

#998 App Conf Example
  .github/workflows/standalone-scenarios.json
  examples/app_config/100-simple/configuration.tfvars
  examples/app_config/README.md
  examples/module.tf
  examples/variables.tf
  modules/databases/app_config/local.dynamic_settings.tf
  variables.tf
Labels: enhancement

#1006 Add Azure Route Server compatibility
  .pre-commit-config.yaml
  examples/networking/route_server/100-simple-route-server/configuration.tfvars
  modules/networking/virtual_wan/virtual_hub/variables.tf
  modules/networking/virtual_wan/virtual_hub/virtual_hub.tf
  networking_virtual_hubs.tf
Labels: enhancement

#1017 Fix remote resources composition bug for VMSS, MSSQL and networking
  azurerm_application_insights.tf
  diagnostics.tf
  modules/compute/container_registry/private_endpoint.tf
  modules/databases/mssql_server/private_endpoints.tf
  mssql_servers.tf
  networking.tf
  virtual_machines_scale_sets.tf
Labels: enhancement

#1022 Refactor diagnostics composition
  diagnostics.tf
  log_analytics.tf
  modules/log_analytics/solutions.tf
  modules/log_analytics/variables.tf
  modules/log_analytics/workspace.tf
Labels: enhancement

#999 add dynamic value to dynamic kv secret
  .github/workflows/standalone-scenarios.json
  examples/keyvault/104-keyvault-dynamic-secret/README.md
  examples/keyvault/104-keyvault-dynamic-secret/configuration.tfvars
  modules/security/dynamic_keyvault_secrets/keyvault.tf
  modules/security/dynamic_keyvault_secrets/secret_dynamic/keyvault_secret.tf
  modules/security/dynamic_keyvault_secrets/secret_dynamic/variables.tf
Labels: new submodule

#1002 Fix prefixes on Azure Virtual Desktop and host pool association
  modules/compute/virtual_machine_extensions/wvd_dsc.tf
  modules/compute/wvd_application_group/virtual_desktop_application_group.tf
  modules/compute/wvd_host_pool/virtual_desktop_host_pool.tf
  modules/compute/wvd_workspace/virtual_desktop_workspace.tf
Labels: bug, enhancement

#997 Add missing value iterator in dynamic private_dns_zone_group block
  modules/networking/private_endpoint/private_endpoint.tf
Labels: bug

#1007 Add private endpoints support to Service Bus Namespace
  examples/servicebus/200-servicebus-privatelink/configuration.tfvars
  messaging_servicebus_namespaces.tf
  modules/messaging/servicebus/namespace/main.tf
  modules/messaging/servicebus/namespace/private_endpoints.tf
  modules/messaging/servicebus/namespace/variables.tf
Labels: bug

#1032 Fix private DNS registration for private_endpoints
  modules/networking/private_endpoint/private_endpoint.tf
Labels: bug

#725 Add cosmosdb_sql_databases module
  cosmosdb_sql_databases.tf
  locals.combined_objects.tf
  locals.tf
  modules/databases/cosmos_dbs/output.tf
  modules/databases/cosmos_dbs/sql_database/output.tf
Labels: new submodule

#1036 Fix APIM private virtual_network_configuration block
  api_management.tf
  examples/apim/115-api_management_private_virtual_network/configuration.tfvars
  modules/apim/api_management/module.tf
  modules/apim/api_management/variables.tf
Labels: bug

#1028 Add key vault reference identity to function app
  modules/webapps/function_app/module.tf
Labels: enhancement

#1040 Example ACI Update GHA runner
  .github/workflows/standalone-scenarios.json
  .pre-commit-config.yaml
  examples/compute/container_groups/100-aci-rover-github-runner/container_groups.tfvars
  examples/compute/container_groups/100-aci-rover-github-runner/global_settings.tfvars
  examples/compute/container_groups/100-aci-rover-github-runner/keyvaults.tfvars
  examples/compute/container_groups/100-aci-rover-github-runner/managed_identities.tfvars
  examples/compute/container_groups/100-aci-rover-github-runner/resource_groups.tfvars
  examples/compute/container_groups/101-aci-nginx/container_groups.tfvars
  examples/compute/container_groups/101-aci-nginx/global_settings.tfvars
  examples/compute/container_groups/101-aci-nginx/keyvaults.tfvars
  examples/compute/container_groups/101-aci-nginx/managed_identities.tfvars
  examples/compute/container_groups/101-aci-nginx/resource_groups.tfvars
Labels: enhancement

#1034 Internal refactoring for SignalR, Service Bus, Data factory, ACR, Databricks, VM
  .github/workflows/standalone-scenarios.json
  active_directory_domain_service.tf
  aks_clusters.tf
  api_management.tf
  app_config.tf
  app_service_environments.tf
  app_service_plans.tf
  app_services.tf
  azuread_service_principal_passwords.tf
  azuread_service_principals.tf
  communication_services.tf
  data_explorer.tf
  data_factory.tf
  data_factory_linked_services.tf
  databricks.tf
  disk_encryption_sets.tf
  examples/app_config/100-simple/configuration.tfvars
  examples/data_factory/116-data_factory_linked_service_azure_databricks/README.md
  examples/data_factory/116-data_factory_linked_service_azure_databricks/configuration.tfvars
  machine_learning.tf
  modules/analytics/databricks_workspace/diagnostics.tf
  modules/analytics/databricks_workspace/main.tf
  modules/analytics/databricks_workspace/variables.tf
  modules/analytics/databricks_workspace/workspace.tf
  modules/azuread/credentials/password.tf
  modules/azuread/groups_members/azuread_groups_membership.tf
  modules/azuread/service_principal/module.tf
  modules/compute/container_registry/main.tf
  modules/compute/container_registry/output.tf
  modules/compute/container_registry/private_endpoint.tf
  modules/compute/container_registry/registry.tf
  modules/compute/virtual_machine/vm_linux.tf
  modules/compute/virtual_machine/vm_windows.tf
  modules/compute/virtual_machine_scale_set/vmss_linux.tf
  modules/compute/virtual_machine_scale_set/vmss_windows.tf
  modules/data_factory/data_factory/main.tf
  modules/data_factory/data_factory/module.tf
  modules/data_factory/data_factory/private_endpoints.tf
  modules/data_factory/data_factory_integration_runtime_azure_ssis/module.tf
  modules/databases/app_config/local.dynamic_settings.tf
  modules/databases/mssql_server/server.tf
  modules/messaging/servicebus/namespace/main.tf
  modules/messaging/servicebus/namespace/network_rule_set/network_rule_set.tf
  modules/messaging/servicebus/queue/main.tf
  modules/messaging/servicebus/topic/main.tf
  modules/messaging/signalr_service/main.tf
  modules/security/disk_encryption_set/disk_encryption_set.tf
  modules/security/disk_encryption_set/variables.tf
  mssql_elastic_pools.tf
  mssql_servers.tf
  netapp.tf
  networking.tf
  networking_dns_zones.tf
  networking_domain_name_registrations.tf
  networking_vngw.tf
  redis_caches.tf
  shared_image_gallery.tf
  virtual_machines.tf
  virtual_machines_scale_sets.tf
Labels: bug

#1027 Enable AAD role assignment for AAD security groups
  azuread_roles.tf
Labels: enhancement

#1020 Add additional secrets for database resources (mariadb, mysql, postgres)
  modules/databases/mariadb_server/server.tf
  modules/databases/mysql_server/server.tf
  modules/databases/postgresql_server/server.tf
Labels: enhancement
