Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2022-01, with the labels that each got.

#866 Update private_endpoint.tf
  modules/networking/private_endpoint/private_endpoint.tf
Labels: bug

#855 Add missing tags to log_analytics solutions
  modules/log_analytics/solutions.tf
Labels: bug

#882 Inject preexisting vnet_id for load balancer
  modules/networking/load_balancers/load_balancers.tf
Labels: enhancement

#878 Allow admin password in VMSS
  modules/compute/virtual_machine_scale_set/vmss_linux.tf
Labels: enhancement

#844 Add automatic repair to vmss, based on a lb probe.
  examples/compute/virtual_machine_scale_set/105-linux-win-vmss-autorepair/configuration.tfvars
  modules/compute/virtual_machine_scale_set/vmss_linux.tf
  modules/compute/virtual_machine_scale_set/vmss_windows.tf
  modules/networking/load_balancers/output.tf
Labels: enhancement, do not merge

#874 System Identity option added to identity in function app
  modules/webapps/function_app/module.tf
Labels: enhancement

#860 SQL VM Module add auto-generate password support
  examples/compute/virtual_machine/108-mssql-vm/configuration.tfvars
  modules/compute/virtual_machine/mssql_vm.tf
Labels: enhancement

#886 No password generated for Linux VM when deploying MSSQL
  modules/compute/virtual_machine/mssql_vm.tf
Labels: bug

#887 Data Disk restore interim fix
  modules/compute/virtual_machine/vm_disk.tf
Labels: enhancement

#889 Inject exiting subnet ids into Key Vault network ACLs
  examples/keyvault/101-keyvault-policies/keyvaults.tfvars
  modules/security/keyvault/keyvault.tf
Labels: enhancement

#892 Unable to refer to subnet_id for SQL Managed Instances
  msssql_managed_instances.tf
Labels: bug

#896 Adding Linux License AHB Variable for Virtual Machine
  modules/compute/virtual_machine/vm_linux.tf
Labels: enhancement

#901 Fix Specify a pre-existing storage account for diagnostics destinations
  examples/diagnostics_profiles/202-reuse-existing-log-analytics/diagnostics_destinations.tfvars
  examples/diagnostics_profiles/202-reuse-existing-log-analytics/virtual_network.tfvars
  modules/diagnostics/module.tf
  modules/networking/virtual_network/nsg/flow_logs/flow_logs.tf
Labels: enhancement

#864 Issue #863 - Azure file share backup
  modules/storage_account/file_share/file_share.tf
Labels: enhancement

#849 Added support for image_registry_credentials to container groups
  container_groups.tf
  examples/compute/container_groups/102-aci-private-registry/container_groups.tfvars
  examples/compute/container_groups/102-aci-private-registry/global_settings.tfvars
  examples/compute/container_groups/102-aci-private-registry/keyvaults.tfvars
  examples/compute/container_groups/102-aci-private-registry/managed_identities.tfvars
  examples/compute/container_groups/102-aci-private-registry/resource_groups.tfvars
  modules/compute/container_group/container_group.tf
  modules/compute/container_group/variables.tf
Labels: enhancement

#865 [nm] added support for azurerm_postgresql_flexible_server*
  .github/workflows/standalone-scenarios.json
  examples/module.tf
  examples/postgresql_flexible_server/100-simple-postgresql-flexible/configuration.tfvars
  examples/postgresql_flexible_server/101-delegated-subnet-with-fw-rule/configurations.tfvars
  examples/postgresql_flexible_server/102-advanced-postgresql-flexible/configurations.tfvars
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/databases/postgresql_flexible_server/configuration.tf
  modules/databases/postgresql_flexible_server/database.tf
  modules/databases/postgresql_flexible_server/diagnostics.tf
  modules/databases/postgresql_flexible_server/firewall_rule.tf
  modules/databases/postgresql_flexible_server/main.tf
  modules/databases/postgresql_flexible_server/output.tf
  modules/databases/postgresql_flexible_server/server.tf
  modules/databases/postgresql_flexible_server/variables.tf
  postgresql_flexible_servers.tf
Labels: new submodule

#906 APIM - Example 107 - API Operation Policy FIX
  api_management.tf
  examples/apim/107-api_operation_policy/configuration.tfvars
  examples/apim/109-api_management_custom_domain/configuration.tfvars
  modules/apim/api_management_api_operation_policy/module.tf
Labels: bug

#899 Add custom script extension for linux VMs
  examples/compute/virtual_machine/110-win-linuxvm-custom-script-extension/configuration.tfvars
  examples/compute/virtual_machine/110-win-linuxvm-custom-script-extension/scripts/helloworld.ps1
  examples/compute/virtual_machine/110-win-linuxvm-custom-script-extension/scripts/helloworld.sh
  examples/vm_extensions.tf
  modules/compute/virtual_machine_extensions/custom_script.tf
  modules/compute/virtual_machine_extensions/variables.tf
Labels: bug
