Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2022-04, with the labels that each got.

#1065 fixed bug for azure firewall management ip id and added example
  examples/networking/firewall/104-firewall-force-tunnelling/configuration.tfvars
  modules/networking/firewall/module.tf
Labels: bug

#1049 Adding public ip prefixes
  .github/workflows/standalone-scenarios.json
  examples/networking/pip_prefix/100-simple-pip-prefix/configuration.tfvars
  examples/networking/pip_prefix/100-simple-pip-prefix/public_ip_addresses.tfvars
  local.remote_objects.tf
  locals.combined_objects.tf
  locals.tf
  modules/networking/public_ip_prefixes/locals.tf
  modules/networking/public_ip_prefixes/main.tf
  modules/networking/public_ip_prefixes/module.tf
  modules/networking/public_ip_prefixes/output.tf
  modules/networking/public_ip_prefixes/variables.tf
  networking.tf
Labels: new submodule, networking

#1052 prevent_duplicate_names instead of identifier_uris
  modules/azuread/applications/module.tf
Labels: bug

#1059 Rename override backend path environment variable
  modules/networking/application_gateway_application/http_settings.tf
  modules/networking/application_gateway_application/scripts/set_resource.sh
Labels: bug, app_gateway

#1067 Fix ip_restriction issues and add improvements for App Service
  .github/workflows/standalone-scenarios.json
  examples/webapps/appservice/109-appservice-appgw/configuration.tfvars
  locals.tf
  modules/webapps/appservice/module.tf
Labels: bug, app_service

#1055 Add role assignments for Log Analytics
  roles.tf
Labels: bug, enhancement

#954 Enable application logging & web server logging storage container sas url to be dynamically obtained
  modules/webapps/appservice/main.tf
  modules/webapps/appservice/storage_account.tf
Labels: enhancement, app_service

#1084 fixed firewall: firewall_policy_key not considered
  networking_firewall.tf
Labels: bug, networking, azure firewall, azure firewall policy

#1056 Added Ansible Playbooks for Linux VM
  examples/compute/virtual_machine/111-single-linux-ansible-playbook/configuration.tfvars
  examples/compute/virtual_machine/111-single-linux-ansible-playbook/nsg.tfvars
  examples/compute/virtual_machine/111-single-linux-ansible-playbook/playbook.yml
  examples/compute/virtual_machine/111-single-linux-ansible-playbook/runbooks.tfvars
  examples/compute/virtual_machine/111-single-linux-ansible-playbook/virtual_machines.tfvars
  locals.tf
  modules/compute/runbooks/ansible_playbook/ansible.tf
  modules/compute/runbooks/ansible_playbook/variables.tf
  runbooks.tf
Labels: new submodule, virtual machines, ansible, linux

#1075 Private DNS Support for remote VNet link
  modules/networking/private-dns/virtual_network_link.tf
Labels: bug, networking, private dns

#1073 Add support for key_vault_reference_identity_id with MSI for App Service
  modules/webapps/appservice/module.tf
  modules/webapps/appservice/slot.tf
Labels: bug, app_service

#1019 Add support for autoscaled VMSS
  modules/compute/virtual_machine_scale_set/output.tf
  modules/compute/virtual_machine_scale_set/vmss_linux.tf
Labels: enhancement

#1088 Fixing #1087
  networking_firewall.tf
Labels: bug

#1089 Patch for #954
  examples/webapps/appservice/105-appservice-backup/configuration.tfvars
  modules/webapps/appservice/main.tf
  modules/webapps/appservice/module.tf
  modules/webapps/appservice/storage_account.tf
Labels: bug

#1104 Feature.virtual hub route table routes
  .github/workflows/standalone-scenarios.json
  examples/module.tf
  examples/networking/virtual_wan/102a-vwan-hub-firewall-secured-vhub-fw-mgr/virtual_wan.tfvars
  examples/variables.tf
  locals.tf
  modules/networking/express_route_connection/module.tf
  modules/networking/virtual_hub_er_gateway_connection/er_connection.tf
  modules/networking/virtual_hub_route_table_routes/main.tf
  modules/networking/virtual_hub_route_table_routes/module.tf
  modules/networking/virtual_hub_route_table_routes/output.tf
  modules/networking/virtual_hub_route_table_routes/variables.tf
  networking_virtual_hub_connection.tf
  networking_virtual_hub_route_table_routes.tf
Labels: enhancement, new submodule

#1099 fix location variables in Data factory module
  data_factory.tf
  modules/data_factory/data_factory/private_endpoints.tf
Labels: bug

#1093 Add Azure Batch
  .github/workflows/standalone-scenarios.json
  batch_accounts.tf
  batch_applications.tf
  batch_certificates.tf
  batch_jobs.tf
  batch_pools.tf
  examples/compute/batch/batch_account/100-batch-account-storage/configuration.tfvars
  examples/compute/batch/batch_account/100-batch-account/configuration.tfvars
  examples/compute/batch/batch_account/200-batch-account-private-endpoint/configuration.tfvars
  examples/compute/batch/batch_account/200-batch-account-user-subscription/configuration.tfvars
  examples/compute/batch/batch_application/100-batch-application/configuration.tfvars
  examples/compute/batch/batch_certificate/100-batch-certificate/certificate.cer
  examples/compute/batch/batch_certificate/100-batch-certificate/configuration.tfvars
  examples/compute/batch/batch_job/100-batch-job/configuration.tfvars
  examples/compute/batch/batch_pool/100-batch-pool/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  local.remote_objects.tf
  locals.combined_objects.tf
  locals.tf
  modules/compute/batch/batch_account/account.tf
  modules/compute/batch/batch_account/diagnostics.tf
  modules/compute/batch/batch_account/main.tf
  modules/compute/batch/batch_account/managed_identities.tf
  modules/compute/batch/batch_account/output.tf
  modules/compute/batch/batch_account/private_endpoint.tf
  modules/compute/batch/batch_account/variables.tf
  modules/compute/batch/batch_application/application.tf
  modules/compute/batch/batch_application/main.tf
  modules/compute/batch/batch_application/output.tf
  modules/compute/batch/batch_application/variables.tf
  modules/compute/batch/batch_certificate/certificate.tf
  modules/compute/batch/batch_certificate/main.tf
  modules/compute/batch/batch_certificate/output.tf
  modules/compute/batch/batch_certificate/variables.tf
  modules/compute/batch/batch_job/job.tf
  modules/compute/batch/batch_job/main.tf
  modules/compute/batch/batch_job/output.tf
  modules/compute/batch/batch_job/variables.tf
  modules/compute/batch/batch_pool/main.tf
  modules/compute/batch/batch_pool/managed_identities.tf
  modules/compute/batch/batch_pool/output.tf
  modules/compute/batch/batch_pool/pool.tf
  modules/compute/batch/batch_pool/variables.tf
  networking_private_links.tf
  roles.tf
Labels: new submodule, compute

#1100 Added optional attributes in vpn_client_configuration
  examples/networking/virtual_network_gateway/105-vpn-point-to-site-gateway-multi-auth/configuration.tfvars
  modules/networking/virtual_network_gateways/module.tf
Labels: enhancement

#1103 Update variables.tf
  modules/compute/virtual_machine/variables.tf
Labels: bug

#1105 Add support for private endpoints in Purview
  .github/workflows/standalone-scenarios.json
  examples/purview/100-purview_account/configuration.tfvars
  examples/purview/101-purview_account_private_link/configuration.tfvars
  modules/purview/purview_accounts/main.tf
  modules/purview/purview_accounts/output.tf
  modules/purview/purview_accounts/private_endpoints.tf
  modules/purview/purview_accounts/variables.tf
  purview.tf
Labels: enhancement

#1091 Add assignable_scopes attribute to custom_roles module
  examples/azuread/101-custom-role-assignable-scopes/configuration.tfvars
  modules/roles/custom_roles/module.tf
  modules/roles/custom_roles/variables.tf
  roles.tf
Labels: enhancement

#1106 remove role assignment lifecycles
  roles.tf
Labels: bug, azuread

#1108 Update image_uri for legacy VM creation method
  modules/compute/virtual_machine/vm_legacy.tf
Labels: bug

#1116 Fix regression in principal_id for roles.tf
  roles.tf
Labels: bug

#1113 Update agw platform to reference keyvault by id to get SSL cert
  modules/networking/application_gateway_platform/application_gateway.tf
Labels: bug, app_gateway

#975 Add provision_after_extensions to custom_script extension
  modules/compute/virtual_machine_scale_set_extensions/custom_script.tf
Labels: enhancement

#862 Adding enabled_protocol to azurerm_storage_share
  .github/workflows/standalone-scenarios.json
  examples/storage_accounts/108-file-share-nfs/configuration.tfvars
  modules/storage_account/file_share/file_share.tf
  modules/storage_account/storage_account.tf
Labels: enhancement, storage services

#1122 Adds support for defining diagnostic profiles to the data factory module
  data_factory.tf
  examples/data_factory/117-data_factory_diagnostics/configuration.tfvars
  modules/data_factory/data_factory/diagnostics.tf
  modules/data_factory/data_factory/variables.tf
Labels: enhancement, data services

#1124 gen2_filesystem - substitute empty map when var.settings.properties i…
  modules/storage_account/data_lake_filesystem/gen2_filesystem.tf
Labels: enhancement

#1072 Added 'assignable_to_role' option for AAD groups
  modules/azuread/groups/group.tf
  modules/azuread/groups/output.tf
  modules/azuread/groups/variables.tf
Labels: azuread, microsoft_graph

#1129 Add public control cosmos db
  examples/cosmos_db/101-private-endpoint-cosmos-db/configuration.tfvars
  modules/databases/cosmos_dbs/cosmosdb_account.tf
Labels: enhancement, data services
