Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2023-11, with the labels that each got.

#1845 Blinq global settings override custom role
  modules/roles/custom_roles/module.tf
Labels: enhancement

#1814 Fix the keyvault request that gets password from keyvault by using valid uri
  keyvault_certificate_requests.tf
  modules/security/keyvault_certificate_request/global_sign.tf
  modules/security/keyvault_certificate_request/output.tf
  modules/security/keyvault_certificate_request/variables.tf
Labels: bug, keyvault

#1841 feat(virtual_hubs): p2s_config keyvault secret
  .github/workflows/standalone-scenarios-longrunners.json
  examples/networking/virtual_wan/110-vwan-hub-gw-p2s-keyvault-cert/virtual_wan.tfvars
  modules/networking/virtual_wan/variables.tf
  modules/networking/virtual_wan/virtual_hub/point_to_site_gateway.tf
  modules/networking/virtual_wan/virtual_hub/variables.tf
  modules/networking/virtual_wan/virtual_wan.tf
  networking_virtual_hubs.tf
  networking_virtual_wan.tf
Labels: enhancement, virtual wan

#1862 Add immutability and public_network_access_enabled to Recovery Vault
  modules/recovery_vault/recovery_vault.tf
Labels: enhancement

#1861 Update for virtual_router_auto_scale_min_capacity attribute
  examples/networking/virtual_wan/106-vwan-hub-routes/virtual_wan.tfvars
  modules/networking/virtual_wan/virtual_hub/point_to_site_gateway.tf
  modules/networking/virtual_wan/virtual_hub/virtual_hub.tf
Labels: virtual wan

#1869 Added policy_type to Recovery Vault Backup Policies
  modules/recovery_vault/backup_policies_vm.tf
Labels: enhancement, recovery vault

#1851 Added tags to eventgrid resources
  eventgrid.tf
Labels: bug

#1852 Added support for different remote LZ for script storage account and …
  modules/compute/virtual_machine_extensions/custom_script.tf
Labels: enhancement

#1792 Add container app module
  .github/workflows/standalone-compute.json
  container_app_dapr_components.tf
  container_app_environment_certificates.tf
  container_app_environment_storages.tf
  container_app_environments.tf
  container_apps.tf
  examples/compute/container_app/101-simple-container-app-env/configuration.tfvars
  examples/compute/container_app/102-simple-private-container-app-env/configuration.tfvars
  examples/compute/container_app/103-private-container-app-env/configuration.tfvars
  examples/module.tf
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/compute/container_app/container_app.tf
  modules/compute/container_app/locals.tf
  modules/compute/container_app/main.tf
  modules/compute/container_app/output.tf
  modules/compute/container_app/variables.tf
  modules/compute/container_app_dapr_component/container_app_dapr_component.tf
  modules/compute/container_app_dapr_component/main.tf
  modules/compute/container_app_dapr_component/output.tf
  modules/compute/container_app_dapr_component/variables.tf
  modules/compute/container_app_environment/container_app_environment.tf
  modules/compute/container_app_environment/main.tf
  modules/compute/container_app_environment/output.tf
  modules/compute/container_app_environment/variables.tf
  modules/compute/container_app_environment_certificate/container_app_environment_certificate.tf
  modules/compute/container_app_environment_certificate/main.tf
  modules/compute/container_app_environment_certificate/output.tf
  modules/compute/container_app_environment_certificate/variables.tf
  modules/compute/container_app_environment_storage/container_app_environment_storage.tf
  modules/compute/container_app_environment_storage/main.tf
  modules/compute/container_app_environment_storage/output.tf
  modules/compute/container_app_environment_storage/variables.tf
Labels: new submodule

#1860 Add servicebus_topics scope for role assignment
  keyvault_certificate_requests.tf
  roles.tf
Labels: enhancement, roles, service_bus

#1824 Add diagnostic on Azure Recovery Service Vault
  .github/workflows/standalone-scenarios.json
  examples/recovery_vault/107-asr-diagnostics/configuration.tfvars
  modules/recovery_vault/diagnostics.tf
  modules/recovery_vault/variables.tf
  recovery_vaults.tf
Labels: enhancement

#1874 Fix error with missing global settings in variable
  modules/roles/custom_roles/module.tf
Labels: bug, azuread
