Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2023-06, with the labels that each got.

#1632 Fix arm_template warnings on sqlmi v0
  examples/module.tf
  examples/mssql_mi/200-mi/configuration.tfvars
  modules/databases/mssql_managed_database/arm_managed_db.json
  modules/databases/mssql_managed_database/backup_ltr/arm_backup_ltr.json
  modules/databases/mssql_managed_database/backup_ltr/backup_ltr.tf
  modules/databases/mssql_managed_database/backup_ltr/main.tf
  modules/databases/mssql_managed_database/backup_ltr/scripts/clear_backup_ltr.sh
  modules/databases/mssql_managed_database/backup_ltr/variables.tf
  modules/databases/mssql_managed_database/main.tf
  modules/databases/mssql_managed_database/managed_database.tf
  modules/databases/mssql_managed_database/output.tf
  modules/databases/mssql_managed_database/scripts/destroy_resource.sh
  modules/databases/mssql_managed_database/variables.tf
  modules/databases/mssql_managed_instance/administrator/mi_administrator.tf
  modules/databases/mssql_managed_instance/administrator/scripts/set_mi_ad_admin.sh
  modules/databases/mssql_managed_instance/arm_sql_mi.json
  modules/databases/mssql_managed_instance/failover_group/mi_failover_group.tf
  modules/databases/mssql_managed_instance/failover_group/scripts/destroy_resource.sh
  modules/databases/mssql_managed_instance/main.tf
  modules/databases/mssql_managed_instance/managed_instance.tf
  modules/databases/mssql_managed_instance/output.tf
  modules/databases/mssql_managed_instance/scripts/destroy_resource.sh
  msssql_managed_databases.tf
Labels: sqlmi

#1640 Set terraform required_version >- 1.3.0
  examples/main.tf
  main.tf
  modules/apim/api_management_api/main.tf
  modules/apim/api_management_api_diagnostic/main.tf
  modules/apim/api_management_api_operation/main.tf
  modules/apim/api_management_api_operation_policy/main.tf
  modules/apim/api_management_api_operation_tag/main.tf
  modules/apim/api_management_api_policy/main.tf
  modules/apim/api_management_backend/main.tf
  modules/apim/api_management_certificate/main.tf
  modules/apim/api_management_custom_domain/main.tf
  modules/apim/api_management_diagnostic/main.tf
  modules/apim/api_management_gateway/main.tf
  modules/apim/api_management_gateway_api/main.tf
  modules/apim/api_management_group/main.tf
  modules/apim/api_management_logger/main.tf
  modules/apim/api_management_product/main.tf
  modules/apim/api_management_subscription/main.tf
  modules/apim/api_management_user/main.tf
  modules/backup_vault/backup_vault_policy_blob_storage/main.tf
  modules/backup_vault/backup_vault_policy_disk/main.tf
  modules/backup_vault/main.tf
  modules/databases/data_explorer/kusto_attached_database_configurations/main.tf
  modules/databases/data_explorer/kusto_cluster_customer_managed_keys/main.tf
  modules/databases/data_explorer/kusto_cluster_principal_assignments/main.tf
  modules/databases/data_explorer/kusto_clusters/main.tf
  modules/databases/data_explorer/kusto_database_principal_assignments/main.tf
  modules/databases/data_explorer/kusto_databases/main.tf
  modules/databases/data_explorer/kusto_eventgrid_data_connections/main.tf
  modules/databases/data_explorer/kusto_eventhub_data_connections/main.tf
  modules/databases/data_explorer/kusto_iothub_data_connections/main.tf
  modules/messaging/eventgrid/eventgrid_domain/main.tf
  modules/messaging/eventgrid/eventgrid_domain_topic/main.tf
  modules/messaging/eventgrid/eventgrid_event_subscription/main.tf
  modules/messaging/eventgrid/eventgrid_topic/main.tf
  modules/messaging/web_pubsub/hub/main.tf
  modules/monitoring/log_analytics_storage_insights/main.tf
  modules/monitoring/monitor_activity_log_alert/main.tf
  modules/monitoring/monitor_metric_alert/main.tf
  modules/networking/lb/main.tf
  modules/networking/lb_backend_address_pool/main.tf
  modules/networking/lb_backend_address_pool_address/main.tf
  modules/networking/lb_nat_pool/main.tf
  modules/networking/lb_nat_rule/main.tf
  modules/networking/lb_outbound_rule/main.tf
  modules/networking/lb_probe/main.tf
  modules/networking/lb_rule/main.tf
  modules/networking/network_interface_backend_address_pool_association/main.tf
  modules/networking/relay_hybrid_connection/main.tf
  modules/networking/relay_namespace/main.tf
Labels: bug

#1639 Fix null value for certificate requests
  keyvault_certificate_requests.tf
Labels: bug

#1647 Add support for vnet resource id in vnet link
  networking_private_dns.tf
Labels: private dns

#1663 Fix managed_rules exclusion
  examples/app_gateway/102-waf-policy/waf.tfvars
  examples/webapps/appservice/109-appservice-appgw/waf.tfvars
  modules/networking/application_gateway_waf_policies/waf_policy.tf
Labels: question

#1673 Allow threat_intel_mode in azurerm_firewall to be set when referencing a virtual_hub
  modules/networking/firewall/module.tf
Labels: bug, azure firewall

#1659 Add Azure RBAC roles for Azure Service Bus Namespace
  roles.tf
Labels: roles
