Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2023-04, with the labels that each got.

#1580 Add support to upload blob content + improvements
  diagnostics.tf
  examples/storage_accounts/100-simple-storage-account-blob-container/configuration.tfvars
  examples/storage_container/101-storage_container/configuration.tfvars
  examples/storage_container/101-storage_container/scripts/devops_runtime_docker.sh
  modules/storage_account/blob/module.tf
  modules/storage_account/blob/output.tf
  modules/storage_account/blob/variables.tf
  modules/storage_account/container/storage_blob.tf
  modules/storage_account/container/variables.tf
  modules/storage_account/storage_account.tf
  modules/storage_account/variables.tf
  roles.tf
  storage_account_blobs.tf
  storage_accounts.tf
  storage_container.tf
  variables.tf
Labels: enhancement

#1579 Add patch_mode argument for windows and linux virtual machine
  examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars
  examples/compute/virtual_machine/101-single-windows-vm/configuration.tfvars
  modules/compute/virtual_machine/vm_linux.tf
  modules/compute/virtual_machine/vm_windows.tf
Labels: virtual machines

#1589 Fix a deferred role assignment regression
  roles.tf
Labels: bug

#1584 Feature/private dns resolver
  .github/workflows/standalone-scenarios.json
  examples/module.tf
  examples/networking/private_dns_resolvers/configuration.tfvars
  examples/variables.tf
  locals.combined_objects.tf
  locals.tf
  modules/networking/private-dns-resolvers/main.tf
  modules/networking/private-dns-resolvers/module.tf
  modules/networking/private-dns-resolvers/output.tf
  modules/networking/private-dns-resolvers/variables.tf
  modules/networking/private_dns_resolvers_dns_forwarding_rulesets/main.tf
  modules/networking/private_dns_resolvers_dns_forwarding_rulesets/module.tf
  modules/networking/private_dns_resolvers_dns_forwarding_rulesets/output.tf
  modules/networking/private_dns_resolvers_dns_forwarding_rulesets/variables.tf
  modules/networking/private_dns_resolvers_forwarding_rules/main.tf
  modules/networking/private_dns_resolvers_forwarding_rules/module.tf
  modules/networking/private_dns_resolvers_forwarding_rules/output.tf
  modules/networking/private_dns_resolvers_forwarding_rules/variables.tf
  modules/networking/private_dns_resolvers_inbound_endpoints/main.tf
  modules/networking/private_dns_resolvers_inbound_endpoints/module.tf
  modules/networking/private_dns_resolvers_inbound_endpoints/output.tf
  modules/networking/private_dns_resolvers_inbound_endpoints/variables.tf
  modules/networking/private_dns_resolvers_outbound_endpoints/main.tf
  modules/networking/private_dns_resolvers_outbound_endpoints/module.tf
  modules/networking/private_dns_resolvers_outbound_endpoints/output.tf
  modules/networking/private_dns_resolvers_outbound_endpoints/variables.tf
  modules/networking/private_dns_resolvers_virtual_network_links/main.tf
  modules/networking/private_dns_resolvers_virtual_network_links/module.tf
  modules/networking/private_dns_resolvers_virtual_network_links/output.tf
  modules/networking/private_dns_resolvers_virtual_network_links/variables.tf
  networking_private_dns_resolver_dns_forwarding_rules.tf
  networking_private_dns_resolver_dns_forwarding_rulesets.tf
  networking_private_dns_resolver_inbound_endpoints.tf
  networking_private_dns_resolver_outbound_endpoints.tf
  networking_private_dns_resolver_virtual_network_links.tf
  networking_private_dns_resolvers.tf
Labels: private dns

#1573 Enhancement: Cert request add support for remote dynamic secret reference
  modules/security/keyvault_certificate_request/global_sign.tf
  modules/security/keyvault_certificate_request/main.tf
Labels: enhancement

#1578 Added AKS Preview registration, Workload Identity
  aks_clusters.tf
  examples/compute/kubernetes_services/104-private-cluster/aks.tfvars
  examples/module.tf
  examples/variables.tf
  modules/compute/aks/aks.tf
  preview_features.tf
  variables.tf
Labels: aks

#1459 Add App Registration API and OAuth Permission Scopes
  .github/workflows/standalone-scenarios.json
  examples/azuread/106-azuread-application-with-api-scopes/configuration.tfvars
  modules/azuread/applications/module.tf
  modules/azuread/applications_v1/azuread_application.tf
Labels: enhancement, azuread

#1592 Update instructions for logicapp standard
  .github/workflows/standalone-scenarios-longrunners.json
  .github/workflows/standalone-scenarios.json
  examples/logic_app/101-integration_service_environment/README.md
  examples/logic_app/101-integration_service_environment/configuration.tfvars
  examples/logic_app/108-logic_app_complex/configuration.tfvars
  examples/logic_app/deprecated-101-integration_service_environment/configuration.tfvars
  examples/logic_app/deprecated-108-logic_app_complex/configuration.tfvars
Labels: bug

#1595 Update create timeout from 60m to 120m
  modules/networking/virtual_wan/virtual_hub/point_to_site_gateway.tf
  modules/networking/virtual_wan/virtual_hub/site_to_site_gateway.tf
Labels: bug, CI

#1594 Fixes issue #1593
  modules/apim/api_management/module.tf
Labels: bug, CI
