Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2024-01, with the labels that each got.

#1888 Resolved #1840 Issue with updating url_path_map
  examples/networking/app_gateway/301-agw-v1/agw_application.tfvars
  modules/networking/application_gateway_application/scripts/set_resource.sh
  modules/networking/application_gateway_application/url_path_map.tf
Labels: bug

#1882 fix(azurerm_eventhub_namespace): fixing for_each reference
  modules/event_hubs/namespaces/event_hub_namespaces.tf
Labels: bug, eventhub

#1884 fix(public_ip_addresses): reverse_fqdn type
  modules/networking/public_ip_addresses/variables.tf
Labels: networking

#1893 Add wait time/delay feature after private endpoint creation for private DNS zone policy
  modules/networking/private_endpoint/private_endpoint.tf
Labels: enhancement, networking, private endpoints

#1889 Add Support of domain_configuration_type parameter
  examples/identity/active_directory_domain_service/100-active_directory_domain_service-replica/configuration.tfvars
  modules/identity/active_directory_domain_service/module.tf
Labels: enhancement, azuread

#1904 feat(aks): add temporary_name_for_rotation
  examples/compute/kubernetes_services/101-single-cluster/aks.tfvars
  modules/compute/aks/aks.tf
Labels: enhancement

#1906 Fixed typo on set_resource.sh
  modules/networking/application_gateway_application/scripts/set_resource.sh
Labels: bug, app_gateway

#1907 Add Search service module
  .github/workflows/standalone-scenarios.json
  examples/module.tf
  examples/search_service/100-search-service-both-apikeys-and-azuread/configuration.tfvars
  examples/search_service/101-search-service-only-api-keys/configuration.tfvars
  examples/search_service/102-search-service-only-azuread/configuration.tfvars
  examples/variables.tf
  local.remote_objects.tf
  locals.combined_objects.tf
  locals.tf
  modules/search_service/main.tf
  modules/search_service/output.tf
  modules/search_service/private_endpoint.tf
  modules/search_service/searchservice.tf
  modules/search_service/variables.tf
  search_service.tf
  variables.tf
Labels: new submodule
