Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2024-05, with the labels that each got.

#1970 Rover with Terraform 1.7.5
  .devcontainer/docker-compose.yml
  .github/workflows/landingzone-scenarios.yaml
  .github/workflows/rover.yaml
  .github/workflows/standalone-compute.yaml
  .github/workflows/standalone-networking.yaml
  .github/workflows/standalone-regressor-tf100.yaml
  .github/workflows/standalone-tf100.yaml
  rover_on_ssh_host.yml
Labels: tooling

#1963 Add Private Endpoint feature for SQL MI module
  .github/workflows/standalone-scenarios-longrunners.json
  examples/mssql_mi/200-mi/configuration.tfvars
  examples/mssql_mi/200-mi/nsg.tfvars
  modules/databases/mssql_managed_instance/private_endpoints.tf
  modules/databases/mssql_managed_instance/variables.tf
  modules/databases/mssql_managed_instance_v1/private_endpoints.tf
  modules/databases/mssql_managed_instance_v1/variables.tf
  msssql_managed_instances.tf
  msssql_managed_instances_v1.tf
Labels: enhancement, private endpoints, sqlmi

#1971 APIM - use existing pip - #1960
  .github/workflows/standalone-scenarios-longrunners.json
  api_management.tf
  examples/apim/118-api_management_platform_stv2/configuration.tfvars
  modules/apim/api_management/module.tf
  modules/apim/api_management/variables.tf
Labels: apim

#1979 Adding FMT on push
  .github/workflows/on_push_fmt.yaml
Labels: enhancement

#1980 Upgrade to TF 1.8.4
  .devcontainer/docker-compose.yml
  .github/workflows/landingzone-scenarios.yaml
  .github/workflows/rover.yaml
  .github/workflows/standalone-compute.yaml
  .github/workflows/standalone-networking.yaml
  .github/workflows/standalone-regressor-tf100.yaml
  .github/workflows/standalone-tf100.yaml
Labels: enhancement

#1982 fix: adding https_only for logic app standard
  modules/logic_app/standard/module.tf
Labels: enhancement

#1983 Add initial mock tests examples and pipelines
  .github/workflows/developer.md
  .github/workflows/pr_dispatch.yaml
  .github/workflows/pr_workflow.yaml
  .tflint.hcl
  examples/tests/README.md
  examples/tests/general.tftest.hcl
  examples/tests/mock/e2e_plan.tftest.hcl
  examples/tests/mock_data/data.tfmock.hcl
  locals.tf
Labels: enhancement, tooling

#1957 Fix VPN Gateway Connection Routing
  examples/networking/virtual_wan/109-vwan-vpn-gateway-connection/virtual_wan.tfvars
  modules/networking/virtual_wan/virtual_hub/output.tf
  modules/networking/vpn_gateway_connection/module.tf
  modules/networking/vpn_gateway_connection/variables.tf
  networking_vpn_gateway_connection.tf
Labels: bug, networking, virtual network gateway

#1988 Update workflow
  .github/workflows/pr_dispatch.yaml
Labels: enhancement, tooling

#1989 Remove token access
  .github/workflows/pr_workflow.yaml
Labels: tooling
