Repository aztfmod/terraform-azurerm-caf, pull requests merged in 2024-06, with the labels that each got.

#1968 Added centralized private endpoint for cognitive services account
  examples/networking/private_links/endpoints/100-azure-open-ai-private-endpoint/configuration.tfvars
  modules/networking/private_links/endpoints/subnet/cognitive_services_account.tf
  networking_private_links.tf
Labels: documentation, enhancement, private endpoints, cognitive services, openai

#1891 fix: (azurerm_servicebus_namespace) private endpoint base_tags
  messaging_servicebus_namespaces.tf
  modules/messaging/servicebus/namespace/main.tf
  modules/messaging/servicebus/namespace/namespace.tf
  modules/messaging/servicebus/namespace/private_endpoints.tf
  modules/messaging/servicebus/namespace/variables.tf
Labels: enhancement

#1992 Update mock tests pipelines and azurerm 3.105.0
  .github/workflows/pr_lint.yaml
  .github/workflows/pr_tests-azuread.yaml
  .github/workflows/pr_tests-compute.yaml
  .github/workflows/pr_tests-dataplat.yaml
  .github/workflows/pr_tests-networking.yaml
  .github/workflows/pr_tests-scenarios.yaml
  .github/workflows/standalone-azuread.json
  .github/workflows/standalone-compute.json
  .github/workflows/standalone-compute.yaml
  .github/workflows/standalone-dataplat.json
  .github/workflows/standalone-networking.json
  .github/workflows/standalone-networking.yaml
  .github/workflows/standalone-regressor-tf100.yaml
  .github/workflows/standalone-scenarios-additional.json
  .github/workflows/standalone-scenarios-longrunners.json
  .github/workflows/standalone-scenarios.json
  .github/workflows/standalone-tf100.yaml
  .github/workflows/weekly_dispatch.yaml
  .github/workflows/weekly_workflow.yaml
  azuread_users.tf
  compute_virtual_machines.tf
  compute_virtual_machines_scale_sets.tf
  examples/apim/118-api_management_platform_stv2/configuration.tfvars
  examples/compute/kubernetes_services/108-single-cluster-remote-adgroup-admin/aks.tfvars
  examples/compute/virtual_machine/113-single-linux-custom-data-template/configuration.tfvars
  examples/databricks_access_connectors/100-databricks_access_connectors/configuration.tfvars
  examples/digital_twins/101-adt-servicebus/configuration.tfvars
  examples/iot/100-iot-hub/configuration.tfvars
  examples/iot/103-iot-hub-with-dps/configuration.tfvars
  examples/main.tf
  examples/maintenance_configuration/200-maintenance-configuration-assignment-vm-windows/configuration.tfvars
  examples/maintenance_configuration/201-maintenance-configuration-assignment-vm-linux/configuration.tfvars
  examples/messaging/servicebus/200-servicebus-privatelink/configuration.tfvars
  examples/mssql_mi/200-mi/configuration.tfvars
  examples/mssql_mi/200-mi/nsg.tfvars
  examples/networking/private_links/endpoints/100-azure-open-ai-private-endpoint/configuration.tfvars
  examples/networking/virtual_network_gateway/103-vpn-site-to-site-connection/configuration.tfvars
  examples/recovery_vault/106-backupvault-with-sqldatabase-saphana/recovery_vaults.tfvars
  examples/role_mapping/102-azure-openai-managed-identity/configuration.tfvars
  examples/search_service/100-search-service-both-apikeys-and-azuread/configuration.tfvars
  examples/search_service/102-search-service-only-azuread/configuration.tfvars
  examples/servicebus/100-servicebus-simple/configuration.tfvars
  examples/synapse_analytics/101-synapse-sparkpool/configuration.tfvars
  examples/tests/mock/e2e_plan.tftest.hcl
  examples/tests/mock_data/data.tfmock.hcl
  examples/variables.tf
  examples/webapps/appservice/103-appservice-extend/configuration.tfvars
  locals.tf
  machine_learning.tf
  main.tf
  modules/apim/api_management_gateway_api/module.tf
  modules/databases/cosmos_dbs/output.tf
  modules/messaging/servicebus/namespace/namespace.tf
  shared_image_gallery.tf
Labels: enhancement, tooling

#1993 Fix mock tests scenarios
  examples/tests/mock_data/data.tfmock.hcl
Labels: tooling

#1994 Adding dependabot configuration
  .github/dependabot.yaml
Labels: enhancement, tooling

#2010 Fixed a Bug with Hourly VM Backup policy.
  compute_virtual_machines.tf
  compute_virtual_machines_scale_sets.tf
  databricks_access_connectors.tf
  modules/analytics/databricks_access_connector/main.tf
  modules/analytics/databricks_access_connector/module.tf
  modules/apim/api_management/module.tf
  modules/compute/container_app_dapr_component/container_app_dapr_component.tf
  modules/compute/virtual_machine/dynamic_custom_data.tf
  modules/compute/virtual_machine/vm_disk.tf
  modules/compute/virtual_machine/vm_linux.tf
  modules/maintenance/assignment_virtual_machine/main.tf
  modules/maintenance/assignment_virtual_machine/module.tf
  modules/maintenance/configuration/module.tf
  modules/maintenance/configuration/outputs.tf
  modules/messaging/servicebus/namespace/private_endpoints.tf
  modules/networking/private_endpoint/private_endpoint.tf
  modules/networking/virtual_wan/virtual_wan.tf
  modules/recovery_vault/backup_policies_vm.tf
  modules/recovery_vault/backup_policies_vm_workload.tf
  modules/recovery_vault/outputs.tf
  modules/roles/custom_roles/module.tf
  msssql_managed_instances.tf
  msssql_managed_instances_v1.tf
  networking_private_links.tf
Labels: bug, virtual machines
